// src/views/post/components/Sidebar/index.vue
<!--
 * @Description:
 * @Author: 安知鱼
 * @Date: 2025-08-04 10:11:57
 * @LastEditTime: 2025-08-08 13:38:29
 * @LastEditors: 安知鱼
-->
<script setup lang="ts">
import { computed } from "vue";
import { useSiteConfigStore } from "@/store/modules/siteConfig";
import AuthorInfoCard from "./components/AuthorInfoCard.vue";
import CardWechat from "./components/CardWechat.vue";
import Sticky from "./components/Sticky.vue";

defineOptions({
  name: "Sidebar"
});

const siteConfigStore = useSiteConfigStore();
const siteConfig = computed(() => siteConfigStore.getSiteConfig);

const authorInfoConfig = computed(() => {
  if (!siteConfig.value?.sidebar?.author?.enable) return null;
  return {
    description: siteConfig.value.sidebar.author.description,
    statusImg: siteConfig.value.sidebar.author.statusImg,
    skills: siteConfig.value.sidebar.author.skills,
    social: siteConfig.value.sidebar.author.social,
    userAvatar: siteConfig.value.USER_AVATAR,
    ownerName: siteConfig.value.frontDesk.siteOwner.name,
    subTitle: siteConfig.value.SUB_TITLE
  };
});

const wechatConfig = computed(() => {
  if (!siteConfig.value?.sidebar?.wechat?.enable) return null;
  return {
    face: siteConfig.value.sidebar.wechat.face,
    backFace: siteConfig.value.sidebar.wechat.backFace,
    blurBackground: siteConfig.value.sidebar.wechat.blurBackground
  };
});
</script>

<template>
  <aside class="aside-content">
    <AuthorInfoCard v-if="authorInfoConfig" :config="authorInfoConfig" />
    <CardWechat v-if="wechatConfig" :config="wechatConfig" />

    <Sticky :config="siteConfig" />
  </aside>
</template>

<style lang="scss" scoped>
.aside-content {
  width: 280px;
  transition: all 0.3s;
  display: flex;
  flex-direction: column;
  gap: 0.625rem;
}

@media (max-width: 992px) {
  .aside-content {
    display: none;
  }
}
</style>

// src/components/home/Sidebar/index.tsx
"use client";

import { useMemo } from "react";
import { useSiteConfigStore } from "@/store/site-config-store";
import { AuthorInfoCard } from "./AuthorInfoCard";
import { CardWechat } from "./CardWechat";
import { CardClock } from "./CardClock";
import { CustomSidebarBlocks } from "./CustomSidebarBlocks";
import { StickyCards } from "./StickyCards";
import styles from "./Sidebar.module.css";

export function Sidebar() {
  const siteConfig = useSiteConfigStore(state => state.siteConfig);

  // 作者信息卡片配置
  const authorInfoConfig = useMemo(() => {
    if (!siteConfig?.sidebar?.author?.enable) return null;
    return {
      description: siteConfig.sidebar.author.description || "",
      statusImg: siteConfig.sidebar.author.statusImg || "",
      skills: siteConfig.sidebar.author.skills || [],
      social: siteConfig.sidebar.author.social || {},
      userAvatar: siteConfig.USER_AVATAR || "",
      ownerName: siteConfig.frontDesk?.siteOwner?.name || "",
      subTitle: siteConfig.SUB_TITLE || "",
    };
  }, [siteConfig]);

  // 微信公众号卡片配置
  const wechatConfig = useMemo(() => {
    if (!siteConfig?.sidebar?.wechat?.enable) return null;
    return {
      face: siteConfig.sidebar.wechat.face || "",
      backFace: siteConfig.sidebar.wechat.backFace || "",
      blurBackground: siteConfig.sidebar.wechat.blurBackground || "",
      link: siteConfig.sidebar.wechat.link,
    };
  }, [siteConfig]);

  // 天气时钟配置
  const clockConfig = useMemo(() => {
    const w = siteConfig?.sidebar?.weather;
    if (!w?.enable || !w.qweather_key) return null;
    return {
      qweatherKey: w.qweather_key,
      qweatherAPIHost: w.qweather_api_host || "devapi.qweather.com",
      ipAPIKey: w.ip_api_key || "",
      loading: w.loading || "",
      defaultRectangle: w.default_rectangle === true || (w.default_rectangle as unknown) === "true",
      rectangle: w.rectangle || "112.6534116,27.96920845",
    };
  }, [siteConfig]);

  return (
    <aside className={styles.asideContent}>
      {authorInfoConfig && <AuthorInfoCard config={authorInfoConfig} />}
      {wechatConfig && <CardWechat config={wechatConfig} />}
      <CustomSidebarBlocks />
      {clockConfig && <CardClock config={clockConfig} />}
      <StickyCards />
    </aside>
  );
}
