// src/components/layout/Footer/index.tsx
/* eslint-disable @next/next/no-img-element */
"use client";

import { useMemo, useState, useEffect, useCallback } from "react";
import Link from "next/link";
import { Icon } from "@iconify/react";
import { Tooltip } from "@/components/ui";
import { useSiteConfigStore } from "@/store/site-config-store";
import { apiClient } from "@/lib/api/client";
import styles from "./Footer.module.css";

interface SocialItem {
  title: string;
  icon: string;
  link: string;
}

interface LinkGroup {
  title: string;
  links: Array<{ title: string; link: string; external?: boolean }>;
}

interface FooterBarLink {
  text: string;
  link: string;
  external?: boolean;
}

interface FriendLink {
  name: string;
  url: string;
}

// 后端渲染的页面路径（不应使用 Next.js 跳转）
const BACKEND_RENDERED_EXTENSIONS = [".xml", ".json", ".txt", ".rss"];

/**
 * 判断是否为图片 URL
 */
const isImageUrl = (icon: string) => {
  return icon && (icon.startsWith("http://") || icon.startsWith("https://"));
};

/**
 * 判断是否为 Iconify 图标（包含 :）
 */
const isIconifyIcon = (icon: string) => {
  return icon && icon.includes(":");
};

/**
 * 判断是否为后端渲染的页面
 */
const isBackendRenderedPath = (link: string) => {
  if (!link) return false;
  const lowerLink = link.toLowerCase();
  return BACKEND_RENDERED_EXTENSIONS.some(ext => lowerLink.endsWith(ext));
};

/**
 * 判断是否为内部链接
 */
const isInternalLink = (link: string) => {
  if (!link) return false;
  if (isBackendRenderedPath(link)) return false;
  return link.startsWith("/") || link.startsWith("#") || (!link.startsWith("http://") && !link.startsWith("https://"));
};

/**
 * 根据配置渲染链接，兼容内部路由、后端渲染页面和 external 开关
 */
function FooterLink({
  href,
  children,
  className,
  title,
  external,
}: {
  href: string;
  children: React.ReactNode;
  className: string;
  title?: string;
  external?: boolean;
}) {
  const openInNewTab = typeof external === "boolean" ? external : !isInternalLink(href);

  if (isInternalLink(href) && !openInNewTab) {
    return (
      <Link className={className} href={href} prefetch={false} title={title}>
        {children}
      </Link>
    );
  }

  return (
    <a
      className={className}
      href={href}
      title={title}
      target={openInNewTab ? "_blank" : undefined}
      rel={openInNewTab ? "noopener external nofollow noreferrer" : undefined}
    >
      {children}
    </a>
  );
}

/**
 * 渲染图标
 */
function SocialIcon({ icon, title }: { icon: string; title: string }) {
  if (isImageUrl(icon)) {
    return <img src={icon} alt={title} className={styles.socialIconImg} />;
  }
  if (isIconifyIcon(icon)) {
    return <Icon icon={icon} className={styles.socialIconIconify} />;
  }
  return null;
}

export function Footer() {
  const siteConfig = useSiteConfigStore(state => state.siteConfig);
  const [displayedFriends, setDisplayedFriends] = useState<FriendLink[]>([]);
  const [isAnimating, setIsAnimating] = useState(false);
  const [rotationCount, setRotationCount] = useState(0);
  const [uptimeStatus, setUptimeStatus] = useState<"loading" | "ok" | "partial" | "error">("loading");
  const [runtimeState, setRuntimeState] = useState({
    days: 0,
    time: "0 小时 0 分 0 秒",
    statusImg: "",
    statusDesc: "",
  });
  // Footer 配置
  const footerConfig = useMemo(() => {
    return {
      socialBar: siteConfig?.footer?.socialBar,
      projectList: siteConfig?.footer?.project?.list || [],
      randomFriendsCount: siteConfig?.footer?.list?.randomFriends || 0,
      owner: siteConfig?.footer?.owner,
      bar: siteConfig?.footer?.bar,
      badge: siteConfig?.footer?.badge,
    };
  }, [siteConfig]);

  // 页脚运行时间配置
  const runtimeConfig = useMemo(() => siteConfig?.footer?.runtime, [siteConfig]);

  // 备案信息
  const icpNumber = siteConfig?.ICP_NUMBER;
  const policeRecordNumber = siteConfig?.POLICE_RECORD_NUMBER;
  const policeRecordIcon = siteConfig?.POLICE_RECORD_ICON;

  // Uptime Kuma 配置
  const uptimeKumaConfig = useMemo(() => {
    const config = siteConfig?.footer?.uptime_kuma;
    if (!config) return null;
    const pageUrl = (config.page_url || "").replace(/\/$/, "");
    // 解析 API 地址和 slug
    const match = pageUrl.match(/^(https?:\/\/[^/]+)\/status\/(.+)$/);
    if (!match) return null;
    return {
      enable: config.enable === true || config.enable === "true",
      api_url: match[1],
      slug: match[2],
      page_url: pageUrl,
    };
  }, [siteConfig]);

  // 版权文本
  const copyrightText = useMemo(() => {
    if (!footerConfig.owner) return "";
    const since = footerConfig.owner.since;
    const author = footerConfig.owner.name;
    const authorLink = footerConfig.bar?.authorLink || "/about";
    const nowYear = new Date().getFullYear();
    let yearRange = String(nowYear);
    if (since && Number(since) !== nowYear) {
      yearRange = `${since} - ${nowYear}`;
    }
    return { yearRange, author, authorLink };
  }, [footerConfig.owner, footerConfig.bar?.authorLink]);

  // 获取随机友链
  const refreshFriendLinks = useCallback(async () => {
    if (isAnimating || footerConfig.randomFriendsCount <= 0) return;

    setIsAnimating(true);
    setRotationCount(prev => prev + 1);

    try {
      const result = await apiClient.get<FriendLink[]>(`/api/public/links/random`, {
        params: { num: footerConfig.randomFriendsCount },
      });
      if (result.code === 200 && result.data?.length > 0) {
        setDisplayedFriends(result.data);
      }
    } catch (error) {
      console.error("获取随机友链失败:", error);
    } finally {
      setTimeout(() => setIsAnimating(false), 300);
    }
  }, [isAnimating, footerConfig.randomFriendsCount]);

  // 获取 Uptime Kuma 状态
  const fetchUptimeKumaStatus = useCallback(async () => {
    if (!uptimeKumaConfig?.enable || !uptimeKumaConfig.api_url || !uptimeKumaConfig.slug) {
      return;
    }

    const apiUrl = `${uptimeKumaConfig.api_url}/api/status-page/heartbeat/${uptimeKumaConfig.slug}`;

    try {
      const response = await fetch(apiUrl);
      if (!response.ok) {
        setUptimeStatus("error");
        return;
      }

      const data = await response.json();
      if (data.heartbeatList) {
        const monitors = Object.values(data.heartbeatList) as Array<Array<{ status: number }>>;
        let hasDown = false;

        for (const heartbeats of monitors) {
          if (heartbeats.length > 0) {
            const latestStatus = heartbeats[heartbeats.length - 1]?.status;
            if (latestStatus !== 1) {
              hasDown = true;
              break;
            }
          }
        }

        setUptimeStatus(hasDown ? "partial" : "ok");
      } else {
        setUptimeStatus("ok");
      }
    } catch {
      setUptimeStatus("error");
    }
  }, [uptimeKumaConfig]);

  /** 计算运行时间并更新上/下班状态，合并为单次 setState 避免多次 re-render */
  const calculateRuntime = useCallback(() => {
    if (!runtimeConfig?.launch_time) return;
    try {
      const launchDate = new Date(runtimeConfig.launch_time);
      const diff = Date.now() - launchDate.getTime();
      const days = Math.floor(diff / (1000 * 3600 * 24));

      const remainder = diff % (1000 * 3600 * 24);
      const h = Math.floor(remainder / (1000 * 3600));
      const m = Math.floor((remainder % (1000 * 3600)) / (1000 * 60));
      const s = Math.floor((remainder % (1000 * 60)) / 1000);

      const hour = new Date().getHours();
      const isWorking = hour >= 9 && hour < 18;

      setRuntimeState({
        days,
        time: `${h} 小时 ${m} 分 ${s} 秒`,
        statusImg: isWorking
          ? (runtimeConfig.work_img || runtimeConfig.offduty_img || "")
          : (runtimeConfig.offduty_img || runtimeConfig.work_img || ""),
        statusDesc: isWorking
          ? (runtimeConfig.work_description || runtimeConfig.offduty_description || "")
          : (runtimeConfig.offduty_description || runtimeConfig.work_description || ""),
      });
    } catch (error) {
      console.error("Invalid launch_time format:", error);
    }
  }, [runtimeConfig]);

  // 运行时间是否实际启用
  const runtimeEnabled = runtimeConfig?.enable === true || runtimeConfig?.enable === "true";

  // 初始化运行时间定时器
  useEffect(() => {
    if (runtimeEnabled && runtimeConfig?.launch_time) {
      calculateRuntime();
      const id = setInterval(calculateRuntime, 1000);
      return () => clearInterval(id);
    }
  }, [runtimeEnabled, runtimeConfig?.launch_time, calculateRuntime]);

  // 初始化加载友链
  useEffect(() => {
    if (footerConfig.randomFriendsCount > 0) {
      refreshFriendLinks();
    }
  }, [footerConfig.randomFriendsCount]); // eslint-disable-line react-hooks/exhaustive-deps

  // 初始化 Uptime Kuma 状态
  useEffect(() => {
    if (uptimeKumaConfig?.enable) {
      fetchUptimeKumaStatus();
      // 每5分钟更新一次状态
      const interval = setInterval(fetchUptimeKumaStatus, 5 * 60 * 1000);
      return () => clearInterval(interval);
    }
  }, [uptimeKumaConfig?.enable, fetchUptimeKumaStatus]);

  // 返回顶部
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  // Uptime 状态文本
  const uptimeStatusText = useMemo(() => {
    switch (uptimeStatus) {
      case "loading":
        return "状态获取中...";
      case "ok":
        return "所有业务正常";
      case "partial":
        return "部分服务异常";
      case "error":
        return "状态获取失败";
      default:
        return "";
    }
  }, [uptimeStatus]);

  // 底部徽章列表（启用且有为有效数组时使用）
  const badgeList = useMemo(() => {
    const enable = footerConfig.badge?.enable;
    if (enable !== true && enable !== "true") return [];
    const list = footerConfig.badge?.list;
    if (!Array.isArray(list) || list.length === 0) return [];
    return list;
  }, [footerConfig.badge]);

  // 如果没有配置则不显示
  const hasContent =
    footerConfig.socialBar ||
    footerConfig.projectList.length > 0 ||
    footerConfig.bar ||
    badgeList.length > 0 ||
    runtimeEnabled;
  if (!hasContent) return null;

  return (
    <footer className={styles.footerContainer}>
      <div className={styles.footerWrap}>
        {/* 社交图标栏 */}
        {footerConfig.socialBar && (
          <div className={styles.footerSocialBar}>
            {/* 左侧社交图标 */}
            {footerConfig.socialBar.left?.map((item: SocialItem) => (
              <a
                key={item.link}
                className={styles.socialLink}
                href={item.link}
                title={item.title}
                target="_blank"
                rel="noopener external nofollow noreferrer"
              >
                <SocialIcon icon={item.icon} title={item.title} />
              </a>
            ))}

            {/* 中间图片（返回顶部） */}
            {footerConfig.socialBar.centerImg && (
              <img
                className={styles.footerBackToTop}
                src={footerConfig.socialBar.centerImg}
                alt="返回顶部"
                title="返回顶部"
                onClick={scrollToTop}
              />
            )}

            {/* 右侧社交图标 */}
            {footerConfig.socialBar.right?.map((item: SocialItem) => (
              <a
                key={item.link}
                className={styles.socialLink}
                href={item.link}
                title={item.title}
                target="_blank"
                rel="noopener external nofollow noreferrer"
              >
                <SocialIcon icon={item.icon} title={item.title} />
              </a>
            ))}
          </div>
        )}

        {/* 链接分组区域 */}
        {(footerConfig.projectList.length > 0 || footerConfig.randomFriendsCount > 0) && (
          <div className={styles.footerLinkGrid}>
            {/* 项目链接分组 */}
            {footerConfig.projectList.map((group: LinkGroup) => (
              <div key={group.title} className={styles.footerGroup}>
                <div className={styles.footerTitle}>{group.title}</div>
                <div className={styles.footerLinks}>
                  {group.links.map(link => (
                    <FooterLink
                      key={link.link}
                      href={link.link}
                      className={styles.footerItem}
                      title={link.title}
                      external={link.external}
                    >
                      {link.title}
                    </FooterLink>
                  ))}
                </div>
              </div>
            ))}

            {/* 随机友链分组 */}
            {footerConfig.randomFriendsCount > 0 && (
              <div className={styles.footerGroup}>
                <div className={styles.footerTitleGroup}>
                  <div className={styles.footerTitle}>友链</div>
                  <button
                    type="button"
                    className={styles.randomFriendsBtn}
                    aria-label="换一批友情链接"
                    title="换一批友情链接"
                    onClick={refreshFriendLinks}
                  >
                    <Icon
                      icon="fa6-solid:arrow-rotate-right"
                      className={isAnimating ? styles.isAnimating : ""}
                      style={{ transform: `rotate(${rotationCount * 360}deg)` }}
                    />
                  </button>
                </div>
                <div className={styles.footerLinks}>
                  {displayedFriends.map((friend, index) => (
                    <a
                      key={`${friend.name}-${friend.url}-${index}`}
                      className={styles.footerItem}
                      href={friend.url}
                      title={friend.name}
                      target="_blank"
                      rel="noopener nofollow"
                    >
                      {friend.name}
                    </a>
                  ))}
                  <Link href="/link" prefetch={false} className={styles.footerItem} title="更多友情链接">
                    更多
                  </Link>
                </div>
              </div>
            )}
          </div>
        )}

        {/* 底部徽章：自定义徽章（如框架、CDN、协议等） */}
        {badgeList.length > 0 && (
          <p className={styles.footerBadges}>
            {badgeList.map((badge, index) => (
              <Tooltip
                key={badge.shields + String(index)}
                content={badge.message}
                placement="top"
                showArrow={false}
                offset={8}
                classNames={{ content: "custom-tooltip-content" }}
              >
                <a
                  className={styles.badgeLink}
                  href={badge.link}
                  target="_blank"
                  rel="external nofollow noreferrer"
                  title={badge.message}
                >
                  <img src={badge.shields} alt={badge.message} />
                </a>
              </Tooltip>
            ))}
          </p>
        )}
      </div>

      {/* 页脚运行时间 */}
      {runtimeEnabled && runtimeConfig?.launch_time && (
        <div className={styles.footerRuntimeBoard}>
          {runtimeState.statusImg && (
            <div className={styles.statusImgRow}>
              <img
                className={styles.statusBadge}
                src={runtimeState.statusImg}
                title={runtimeState.statusDesc}
                alt="工作状态"
                onError={e => { (e.target as HTMLImageElement).style.display = "none"; }}
              />
            </div>
          )}
          <div className={styles.runtimeInfoRow}>
            <span className={styles.runtimeText}>
              本站居然运行了 {runtimeState.days} 天
            </span>
            <span className={styles.runtimeTimeText}>{runtimeState.time}</span>
            <Icon icon="fa:heartbeat" className={styles.heartbeatIcon} style={{ color: "red" }} />
          </div>
        </div>
      )}

      {/* Footer Bottom Bar */}
      {footerConfig.bar && (
        <div className={styles.footerBottomBar}>
          <div className={styles.barContent}>
            {/* 左侧：版权信息和备案号 */}
            <div className={styles.barLeft}>
              {/* 版权信息 */}
              {copyrightText && (
                <div className={styles.copyrightInfo}>
                  &copy;{copyrightText.yearRange} By{" "}
                  <a className={styles.barLink} href={copyrightText.authorLink} target="_blank" rel="noopener">
                    {copyrightText.author}
                  </a>
                </div>
              )}

              {/* 备案信息 */}
              {(policeRecordNumber || icpNumber || uptimeKumaConfig?.enable) && (
                <div className={styles.recordInfo}>
                  {/* 公安备案 */}
                  {policeRecordNumber && (
                    <Tooltip
                      content="前往全国互联网安全管理服务平台的备案信息查询页面"
                      placement="top"
                      showArrow={false}
                      offset={8}
                      classNames={{ content: "custom-tooltip-content" }}
                    >
                      <a
                        className={`${styles.recordLink} ${styles.policeRecordLink}`}
                        href="http://www.beian.gov.cn/portal/registerSystemInfo"
                        target="_blank"
                        rel="noopener"
                      >
                        {policeRecordIcon && (
                          <img src={policeRecordIcon} alt="公安备案" className={styles.policeRecordIcon} />
                        )}
                        {policeRecordNumber}
                      </a>
                    </Tooltip>
                  )}

                  {/* ICP 备案 */}
                  {icpNumber && (
                    <Tooltip
                      content="前往工业和信息化部政务服务平台的备案信息查询页面"
                      placement="top"
                      showArrow={false}
                      offset={8}
                      classNames={{ content: "custom-tooltip-content" }}
                    >
                      <a className={styles.recordLink} href="https://beian.miit.gov.cn/" target="_blank" rel="noopener">
                        {icpNumber}
                      </a>
                    </Tooltip>
                  )}

                  {/* Uptime Kuma 状态 */}
                  {uptimeKumaConfig?.enable && (
                    <Tooltip
                      content="查看我的项目状态"
                      placement="top"
                      showArrow={false}
                      offset={8}
                      classNames={{ content: "custom-tooltip-content" }}
                    >
                      <a
                        className={`${styles.uptimeStatusIndicator} ${
                          styles[`status${uptimeStatus.charAt(0).toUpperCase() + uptimeStatus.slice(1)}`]
                        }`}
                        href={uptimeKumaConfig.page_url || "#"}
                        target={uptimeKumaConfig.page_url ? "_blank" : undefined}
                        rel="noopener"
                      >
                        <span className={styles.statusDot} />
                        <span className={styles.statusText}>{uptimeStatusText}</span>
                      </a>
                    </Tooltip>
                  )}
                </div>
              )}
            </div>

            {/* 右侧：链接列表和 CC 协议 */}
            <div className={styles.barRight}>
              {/* 链接列表 */}
              {footerConfig.bar.linkList?.map((link: FooterBarLink) => (
                <FooterLink key={link.text} href={link.link} className={styles.barLink} external={link.external}>
                  {link.text}
                </FooterLink>
              ))}

              {/* CC 协议图标 */}
              {footerConfig.bar.cc?.link && (
                <Tooltip
                  content="CC BY-NC-ND 4.0 协议"
                  placement="top"
                  showArrow={false}
                  offset={8}
                  classNames={{ content: "custom-tooltip-content" }}
                >
                  <a
                    className={`${styles.barLink} ${styles.ccLink}`}
                    href={footerConfig.bar.cc.link}
                    aria-label="CC BY-NC-ND 4.0 协议"
                    target="_blank"
                    rel="noopener"
                  >
                    <Icon icon="ri:copyright-line" />
                    <Icon icon="ri:creative-commons-by-line" />
                    <Icon icon="ri:creative-commons-nc-line" />
                    <Icon icon="ri:creative-commons-nd-line" />
                  </a>
                </Tooltip>
              )}
            </div>
          </div>
        </div>
      )}
    </footer>
  );
}

// src/layout/frontend/components/footer/index.vue
<template>
  <footer
    v-if="siteConfig"
    id="footer-container"
    ref="footerRef"
    class="footer-container"
  >
    <div class="footer-wrap">
      <div v-if="footerConfig.socialBar" class="footer-social-bar">
        <el-tooltip
          v-for="item in footerConfig.socialBar.left"
          :key="item.link"
          :content="item.title"
          placement="top"
          :show-arrow="false"
          :offset="12"
          popper-class="custom-tooltip"
          :transition-props="{ onEnter, onLeave }"
        >
          <a
            class="social-link"
            :href="item.link"
            target="_blank"
            rel="noopener external nofollow noreferrer"
          >
            <!-- 图片 URL -->
            <img
              v-if="isImageUrl(item.icon)"
              :src="item.icon"
              :alt="item.title"
              class="social-icon-img"
            />
            <!-- Iconify 图标 -->
            <IconifyIconOnline
              v-else-if="isIconifyIcon(item.icon)"
              :icon="item.icon"
              class="social-icon-iconify"
            />
            <!-- 其他图标 (anzhiyu/fa) -->
            <i v-else :class="getIconClass(item.icon)" />
          </a>
        </el-tooltip>

        <el-tooltip
          v-if="footerConfig.socialBar.centerImg"
          content="返回顶部"
          placement="top"
          :show-arrow="false"
          :offset="12"
          popper-class="custom-tooltip"
          :transition-props="{ onEnter, onLeave }"
          @click="scrollToTop"
        >
          <img
            class="footer-back-to-top lazy-image"
            alt="返回顶部"
            :data-src="footerConfig.socialBar.centerImg"
            src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMSIgaGVpZ2h0PSIxIiB2aWV3Qm94PSIwIDAgMSAxIiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgo8cmVjdCB3aWR0aD0iMSIgaGVpZ2h0PSIxIiBmaWxsPSJ0cmFuc3BhcmVudCIvPgo8L3N2Zz4="
            width="50"
            height="50"
            loading="lazy"
            @click="scrollToTop"
          />
        </el-tooltip>

        <el-tooltip
          v-for="item in footerConfig.socialBar.right"
          :key="item.link"
          :content="item.title"
          placement="top"
          :show-arrow="false"
          :offset="12"
          popper-class="custom-tooltip"
          :transition-props="{ onEnter, onLeave }"
        >
          <a
            class="social-link"
            :href="item.link"
            target="_blank"
            rel="noopener external nofollow noreferrer"
          >
            <!-- 图片 URL -->
            <img
              v-if="isImageUrl(item.icon)"
              :src="item.icon"
              :alt="item.title"
              class="social-icon-img"
            />
            <!-- Iconify 图标 -->
            <IconifyIconOnline
              v-else-if="isIconifyIcon(item.icon)"
              :icon="item.icon"
              class="social-icon-iconify"
            />
            <!-- 其他图标 (anzhiyu/fa) -->
            <i v-else :class="getIconClass(item.icon)" />
          </a>
        </el-tooltip>
      </div>

      <div v-if="footerConfig.project?.list?.length" class="footer-link-grid">
        <div
          v-for="group in footerConfig.project.list"
          :key="group.title"
          class="footer-group"
        >
          <div class="footer-title">{{ group.title }}</div>
          <div class="footer-links">
            <a
              v-for="link in group.links"
              :key="link.link"
              class="footer-item"
              :href="link.link"
              :title="link.title"
              target="_blank"
              rel="noopener"
            >
              {{ link.title }}
            </a>
          </div>
        </div>

        <div v-if="footerConfig.list?.randomFriends > 0" class="footer-group">
          <div class="footer-title-group">
            <div class="footer-title">友链</div>
            <el-tooltip
              content="换一批友情链接"
              placement="top"
              :show-arrow="false"
              :offset="8"
              popper-class="custom-tooltip"
              :transition-props="{ onEnter, onLeave }"
            >
              <a
                class="random-friends-btn"
                href="javascript:void(0);"
                @click="refreshFriendLinks"
              >
                <i
                  class="anzhiyufont anzhiyu-icon-arrow-rotate-right"
                  :class="{ 'is-animating': isAnimating }"
                  :style="{ transform: `rotate(${rotationCount * 360}deg)` }"
                />
              </a>
            </el-tooltip>
          </div>
          <div class="footer-links">
            <a
              v-for="friend in displayedFriends"
              :key="friend.name"
              class="footer-item"
              :href="friend.href"
              :title="friend.name"
              target="_blank"
              rel="noopener nofollow"
            >
              {{ friend.name }}
            </a>
            <router-link to="/link" class="footer-item" title="更多友情链接"
              >更多</router-link
            >
          </div>
        </div>
      </div>

      <!-- 页脚运行时间模块 -->
      <div
        v-if="footerConfig.runtime?.enable && footerConfig.runtime?.launch_time"
        class="footer-runtime-board"
      >
        <div v-if="currentStatusImg" class="status-img-row">
          <img
            class="status-badge"
            :src="currentStatusImg"
            :title="currentStatusDesc"
            alt="工作状态"
          />
        </div>
        <div class="runtime-info-row">
          <span class="runtime-text">
            本站居然运行了 {{ runtimeDays }} 天
          </span>
          <span class="runtime-time">
            {{ runtimeTime }}
          </span>
          <component
            :is="useRenderIcon('fa:heartbeat', { style: { color: 'red' } })"
            class="heartbeat-icon"
          />
        </div>
      </div>

      <div
        v-if="footerConfig.custom_text"
        class="footer-custom-text"
        v-html="footerConfig.custom_text"
      />

      <p
        v-if="footerConfig.badge?.enable && footerConfig.badge?.list?.length"
        class="footer-badges"
      >
        <el-tooltip
          v-for="badge in footerConfig.badge.list"
          :key="badge.shields"
          :content="badge.message"
          placement="top"
          :show-arrow="false"
          :offset="8"
          popper-class="custom-tooltip"
          :transition-props="{ onEnter, onLeave }"
        >
          <a
            class="badge-link"
            target="_blank"
            :href="badge.link"
            rel="external nofollow noreferrer"
          >
            <img :src="badge.shields" :alt="badge.message" />
          </a>
        </el-tooltip>
      </p>
    </div>

    <div v-if="footerConfig.bar" class="footer-bottom-bar">
      <div class="bar-content">
        <div class="bar-left">
          <div
            v-if="footerConfig.owner"
            class="copyright-info"
            v-html="copyrightText"
          />
        </div>
        <div class="bar-right">
          <template v-for="link in footerConfig.bar.linkList" :key="link.text">
            <router-link
              v-if="isInternalLink(link.link)"
              :to="link.link"
              class="bar-link"
            >
              {{ link.text }}
            </router-link>
            <a
              v-else
              class="bar-link"
              :href="link.link"
              target="_blank"
              rel="noopener"
            >
              {{ link.text }}
            </a>
          </template>
          <el-tooltip
            v-if="icpNumber"
            content="前往工业和信息化部政务服务平台的备案信息查询页面"
            placement="top"
            :show-arrow="false"
            :offset="8"
            popper-class="custom-tooltip"
            :transition-props="{ onEnter, onLeave }"
          >
            <a
              class="bar-link"
              href="https://beian.miit.gov.cn/"
              target="_blank"
              rel="noopener"
            >
              {{ icpNumber }}
            </a>
          </el-tooltip>
          <el-tooltip
            v-if="policeRecordNumber"
            content="前往全国互联网安全管理服务平台的备案信息查询页面"
            placement="top"
            :show-arrow="false"
            :offset="8"
            popper-class="custom-tooltip"
            :transition-props="{ onEnter, onLeave }"
          >
            <a
              class="bar-link police-record-link"
              href="http://www.beian.gov.cn/portal/registerSystemInfo"
              target="_blank"
              rel="noopener"
            >
              <img
                v-if="policeRecordIcon"
                :src="policeRecordIcon"
                alt="公安备案"
                class="police-record-icon"
              />
              {{ policeRecordNumber }}
            </a>
          </el-tooltip>

          <el-tooltip
            v-if="footerConfig.bar.cc && footerConfig.bar.cc.link"
            content="CC BY-NC-ND 4.0 协议"
            placement="top"
            :show-arrow="false"
            :offset="8"
            popper-class="custom-tooltip"
            :transition-props="{ onEnter, onLeave }"
          >
            <a
              class="bar-link cc-link"
              :href="footerConfig.bar.cc.link"
              target="_blank"
              rel="noopener"
            >
              <i class="anzhiyufont anzhiyu-icon-copyright-line" />
              <i class="anzhiyufont anzhiyu-icon-creative-commons-by-line" />
              <i class="anzhiyufont anzhiyu-icon-creative-commons-nc-line" />
              <i class="anzhiyufont anzhiyu-icon-creative-commons-nd-line" />
            </a>
          </el-tooltip>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from "vue";
import { useSiteConfigStore } from "@/store/modules/siteConfig";
import { onEnter, onLeave } from "@/utils/transitions";
import { getIconClass } from "@/utils/icon";
import { getRandomLinks } from "@/api/postLink";
import { useLazyLoading } from "@/composables/useLazyLoading";
import { useRenderIcon } from "@/components/ReIcon/src/hooks";
import { IconifyIconOnline } from "@/components/ReIcon";

// 判断是否为图片 URL
const isImageUrl = (icon: string) => {
  return icon && (icon.startsWith("http://") || icon.startsWith("https://"));
};

// 判断是否为 Iconify 图标（包含 :）
const isIconifyIcon = (icon: string) => {
  return icon && icon.includes(":");
};

// 判断是否为内部链接
const isInternalLink = (link: string) => {
  if (!link) return false;
  return (
    link.startsWith("/") ||
    link.startsWith("#") ||
    (!link.startsWith("http://") && !link.startsWith("https://"))
  );
};

interface FriendLink {
  name: string;
  href: string;
}

const siteConfigStore = useSiteConfigStore();
const siteConfig = computed(() => siteConfigStore.getSiteConfig);
const footerConfig = computed(() => siteConfig.value?.footer);
const icpNumber = computed(() => siteConfig.value?.ICP_NUMBER);
const policeRecordNumber = computed(
  () => siteConfig.value?.POLICE_RECORD_NUMBER
);
const policeRecordIcon = computed(() => siteConfig.value?.POLICE_RECORD_ICON);

const displayedFriends = ref<FriendLink[]>([]);
const rotationCount = ref(0);
const isAnimating = ref(false);

// 懒加载相关
const footerRef = ref<HTMLElement | null>(null);
const { initLazyLoading } = useLazyLoading({
  rootMargin: "50px",
  threshold: 0.1,
  showLoading: true
});

async function refreshFriendLinks() {
  if (isAnimating.value) return;
  if (!footerConfig.value?.list?.randomFriends) return;

  const count = Number(footerConfig.value.list.randomFriends);
  if (count <= 0) return;

  // 立即触发动画以提供即时反馈
  isAnimating.value = true;
  rotationCount.value++;

  try {
    const res = await getRandomLinks({ num: count });
    if (res.code === 200 && res.data && res.data.length > 0) {
      // 将 API 返回的数据映射为模板所需的格式
      displayedFriends.value = res.data.map(link => ({
        name: link.name,
        href: link.url
      }));
    } else {
      console.error("未能获取到随机友链或返回数据为空");
      displayedFriends.value = []; // 如果获取失败或无数据，清空列表
    }
  } catch (error) {
    console.error("请求随机友链失败", error);
    displayedFriends.value = []; // 出错时也清空列表
  } finally {
    // 等待动画结束后再重置状态
    setTimeout(() => {
      isAnimating.value = false;
    }, 300);
  }
}

const copyrightText = computed(() => {
  if (!footerConfig.value?.owner) return "";
  const since = footerConfig.value.owner.since;
  const author = footerConfig.value.owner.name;
  const authorLink = footerConfig.value.bar?.authorLink || "/about";
  const nowYear = new Date().getFullYear();
  let yearRange = String(nowYear);
  if (since && Number(since) !== nowYear) yearRange = `${since} - ${nowYear}`;
  const authorHtml = `<a class="bar-link" href="${authorLink}" target="_blank">${author}</a>`;
  return `&copy;${yearRange} By ${authorHtml}`;
});

const scrollToTop = () => {
  window.scrollTo({ top: 0, behavior: "smooth" });
};

// 运行时间相关
const runtimeDays = ref(0);
const runtimeTime = ref("0 小时 0 分 0 秒");
const currentStatusImg = ref("");
const currentStatusDesc = ref("");
let runtimeInterval: number | null = null;

// 判断是否在工作时间（9:00-18:00）
const isWorkingHours = () => {
  const now = new Date();
  const hour = now.getHours();
  return hour >= 9 && hour < 18;
};

// 计算运行时间
const calculateRuntime = () => {
  if (!footerConfig.value?.runtime?.launch_time) return;

  try {
    const launchDate = new Date(footerConfig.value.runtime.launch_time);
    const currentDate = new Date();
    const differenceInTime = currentDate.getTime() - launchDate.getTime();

    // 计算天数
    runtimeDays.value = Math.floor(differenceInTime / (1000 * 3600 * 24));

    // 计算剩余的小时、分钟、秒
    const remainingTime = differenceInTime % (1000 * 3600 * 24);
    const hours = Math.floor(remainingTime / (1000 * 3600));
    const minutes = Math.floor((remainingTime % (1000 * 3600)) / (1000 * 60));
    const seconds = Math.floor((remainingTime % (1000 * 60)) / 1000);

    runtimeTime.value = `${hours} 小时 ${minutes} 分 ${seconds} 秒`;

    // 更新状态图和描述
    if (isWorkingHours()) {
      currentStatusImg.value = footerConfig.value.runtime?.work_img || "";
      currentStatusDesc.value =
        footerConfig.value.runtime?.work_description || "";
    } else {
      currentStatusImg.value = footerConfig.value.runtime?.offduty_img || "";
      currentStatusDesc.value =
        footerConfig.value.runtime?.offduty_description || "";
    }
  } catch (error) {
    console.error("Invalid launch_time format:", error);
  }
};

onMounted(() => {
  if (footerConfig.value) refreshFriendLinks();
  // 初始化footer区域的懒加载
  if (footerRef.value) {
    initLazyLoading(footerRef.value);
  }

  // 初始化运行时间
  if (footerConfig.value?.runtime?.enable) {
    calculateRuntime();
    // 每秒更新一次运行时间
    runtimeInterval = window.setInterval(calculateRuntime, 1000);
  }
});

onUnmounted(() => {
  // 清除定时器
  if (runtimeInterval) {
    clearInterval(runtimeInterval);
  }
});
</script>

<style scoped lang="scss">
.footer-container {
  position: relative;
  margin-top: 1rem;
  color: var(--anzhiyu-fontcolor);
  background: linear-gradient(
    180deg,
    var(--anzhiyu-card-bg-none) 0,
    var(--anzhiyu-card-bg) 25%
  );
  /* 防止布局偏移：隔离布局计算 */
  contain: layout style;
}

.footer-wrap {
  position: relative;
  max-width: 1200px;
  /* 固定高度防止布局偏移 */
  min-height: 17.875rem;
  margin: 0 auto;
  /* 隔离内容布局 */
  contain: layout;
}

a {
  color: var(--anzhiyu-fontcolor);
  text-decoration: none;

  &:hover {
    color: var(--anzhiyu-main);
  }
}

.footer-social-bar {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  padding: 1rem 0;

  .social-link {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    margin: 1rem 27px;
    font-size: 1.5rem;
    color: var(--anzhiyu-card-bg);
    background: var(--anzhiyu-fontcolor);
    border-radius: 3rem;
    transition: 0.3s;

    .social-icon-img {
      width: 1.2rem;
      height: 1.2rem;
      border-radius: 50%;
      object-fit: cover;
    }

    .social-icon-iconify {
      width: 1.2rem;
      height: 1.2rem;
    }

    &:hover {
      color: var(--anzhiyu-white);
      background: var(--anzhiyu-main);
      transform: scale(1.2);
    }
  }
}

.footer-back-to-top {
  width: 50px;
  height: 50px;
  margin: 0 1rem;
  cursor: pointer;
  object-fit: cover;
  border-radius: 50%;
  transition: cubic-bezier(0, 0, 0, 1.29) 0.5s !important;
  /* 防止图片加载导致的布局偏移 */
  display: inline-block;
  vertical-align: middle;

  &:hover {
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    -webkit-transform-style: preserve-3d;
    transform-style: preserve-3d;
    transform: scale(1.2);
  }
}

.footer-link-grid {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  padding: 0 2rem;
}

.footer-group {
  min-width: 130px;
  text-align: left;
}

.footer-title-group {
  display: flex;
  align-items: center;
}

.footer-title {
  margin-bottom: 0.8rem;
  margin-left: 4px;
  font-size: 1.1rem;
  font-weight: bold;
  color: var(--anzhiyu-secondtext);
}

.random-friends-btn {
  display: flex;
  align-items: center;
  margin-bottom: 0.8rem;
  margin-left: 0.5rem;
  font-size: 1.1rem;
  cursor: pointer;

  > i {
    display: inline-block;
    transition:
      transform 0.3s ease-out,
      opacity 0.3s ease-out;

    &.is-animating {
      opacity: 0.2;
    }
  }
}

.footer-links .footer-item {
  display: block;
  width: fit-content;
  max-width: 120px;
  padding: 0 4px;
  margin-right: 10px;
  margin-bottom: 0.5rem;
  overflow: hidden;
  font-size: 0.95rem;
  text-overflow: ellipsis;
  white-space: nowrap;
  border-radius: 7px;

  &:hover {
    color: white;
    background: var(--anzhiyu-theme);
  }
}

.footer-custom-text {
  padding: 1rem 0;
  font-size: 0.9rem;
  color: var(--anzhiyu-gray);
  text-align: center;
}

.footer-badges {
  padding: 1.5rem 0;
  margin: 0;
  text-align: center;
}

.badge-link {
  display: inline-block;
  margin: 5px;

  img {
    height: 20px;
    vertical-align: middle;
  }
}

.footer-bottom-bar {
  display: flex;
  padding: 1rem;
  margin-top: 1rem;
  overflow: hidden;
  color: var(--anzhiyu-fontcolor);
  background: var(--anzhiyu-secondbg);
  transition: 0.3s;
}

.bar-content {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  max-width: 1400px;
  margin: 0 auto;
  line-height: 1;
}

.bar-left,
.bar-right {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  align-items: center;
  min-height: 32px;
}

.copyright-info :deep(a:hover) {
  color: var(--anzhiyu-main);
}

:deep(.bar-link),
.bar-link {
  margin-top: 8px;
  margin-bottom: 8px;
  font-size: 1rem;
  font-weight: 700;
  color: var(--anzhiyu-fontcolor);
  white-space: nowrap;
  text-decoration: none;

  &:hover {
    color: var(--anzhiyu-main);
  }
}

.cc-link {
  display: flex;
  align-items: center;

  i {
    margin: 0 2px;
  }
}

.police-record-link {
  display: inline-flex;
  align-items: center;
  gap: 4px;

  .police-record-icon {
    width: 14px;
    height: 14px;
    object-fit: contain;
  }
}

@media (width >= 1200) {
  .footer-link-grid {
    gap: 8rem;
  }
}

// 页脚运行时间模块样式
.footer-runtime-board {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.75rem;
  padding: 1rem 2rem;
  margin: 1rem 0;
  font-size: 12px;
  color: var(--anzhiyu-fontcolor);

  .status-img-row {
    display: flex;
    justify-content: center;

    .status-badge {
      width: 100%;
      max-width: 130px;
      height: auto;
      border-radius: 0;
    }
  }

  .runtime-info-row {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    flex-wrap: wrap;

    .runtime-text {
      font-weight: 500;
      line-height: 1.5;
    }

    .runtime-time {
      display: inline-block;
      font-weight: 600;
      border-radius: 10px;
      text-align: center;
    }

    .heartbeat-icon {
      display: inline-flex;
      align-items: center;
      font-size: 16px;
      animation: heartbeat 1.3s ease-in-out infinite;
    }
  }

  @keyframes heartbeat {
    0%,
    100% {
      transform: scale(1);
    }
    10%,
    30% {
      transform: scale(0.9);
    }
    20%,
    40%,
    60%,
    80% {
      transform: scale(1.1);
    }
    50%,
    70% {
      transform: scale(1.05);
    }
  }
}

// 懒加载相关样式
.lazy-image {
  background-color: var(--anzhiyu-secondbg);
  background-image: linear-gradient(
    90deg,
    transparent,
    rgba(255, 255, 255, 0.04),
    transparent
  );
  background-size: 200% 100%;
  animation: loading 1.5s infinite;

  &.lazy-loading {
    filter: blur(5px);
    transition: filter 0.3s ease;
  }

  &.lazy-loaded {
    animation: none;
    background: none;
    filter: none;
  }

  &.lazy-error {
    background: var(--anzhiyu-secondbg);
    opacity: 0.5;
  }
}

@keyframes loading {
  0% {
    background-position: 200% 0;
  }
  100% {
    background-position: -200% 0;
  }
}

@media (width <= 768px) {
  .footer-back-to-top {
    display: none;
  }
  .footer-container {
    z-index: 99;
    background: var(--anzhiyu-card-bg);
    margin-top: -1px;
    width: 100%;
    max-width: 100%;
    overflow-x: hidden;
    touch-action: pan-y;
  }
}
</style>
