// src/components/RightMenu/index.tsx
"use client";

/**
 * @Description: 右键菜单组件
 * @Author: 安知鱼
 * 1:1 移植自 anheyu-pro layout/frontend/components/RightMenu/index.vue
 */
import { useState, useRef, useEffect, useCallback } from "react";
import { useRouter, usePathname } from "next/navigation";
import { useTheme } from "next-themes";
import { Icon } from "@iconify/react";
import { addToast } from "@heroui/react";
import { useUiStore } from "@/store/ui-store";
import { useSiteConfigStore } from "@/store/site-config-store";
import styles from "./styles.module.css";

/**
 * 安全写入剪贴板（带错误处理）
 */
const safeClipboardWrite = (text: string, successMsg: string) => {
  navigator.clipboard.writeText(text).then(
    () => addToast({ title: successMsg, color: "success", timeout: 2000 }),
    () => addToast({ title: "复制失败，请重试", color: "danger", timeout: 2000 })
  );
};

export function RightMenu() {
  const router = useRouter();
  const pathname = usePathname();
  const { theme, setTheme } = useTheme();

  const useCustomContextMenu = useUiStore(s => s.useCustomContextMenu);
  const isCommentBarrageVisible = useUiStore(s => s.isCommentBarrageVisible);
  const toggleCommentBarrage = useUiStore(s => s.toggleCommentBarrage);
  const siteConfig = useSiteConfigStore(s => s.siteConfig);

  const [isVisible, setIsVisible] = useState(false);
  const [isHiding, setIsHiding] = useState(false);
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const [transformOrigin, setTransformOrigin] = useState("top left");
  const [isTextSelected, setIsTextSelected] = useState(false);
  const [capturedText, setCapturedText] = useState("");
  const [isTextInPostDetail, setIsTextInPostDetail] = useState(false);
  const [hasCommentSection, setHasCommentSection] = useState(false);
  const [isClickOnMusicPlayer, setIsClickOnMusicPlayer] = useState(false);
  const [musicIsPlaying, setMusicIsPlaying] = useState(false);

  const menuRef = useRef<HTMLDivElement>(null);
  const hideTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isVisibleRef = useRef(false);
  const isDark = theme === "dark";

  // 使用 ref 稳定引用，避免事件监听器频繁重注册
  const stateRef = useRef({
    useCustomContextMenu,
    pathname,
    siteConfig,
  });

  // 同步 ref（放在 useEffect 中避免 lint 警告）
  useEffect(() => {
    isVisibleRef.current = isVisible;
  }, [isVisible]);

  useEffect(() => {
    stateRef.current = { useCustomContextMenu, pathname, siteConfig };
  }, [useCustomContextMenu, pathname, siteConfig]);

  // 隐藏菜单（用 ref 读取 isVisible，避免 stale closure）
  const hideMenu = useCallback(() => {
    if (!isVisibleRef.current) return;
    if (hideTimerRef.current) clearTimeout(hideTimerRef.current);
    setIsHiding(true);
    hideTimerRef.current = setTimeout(() => {
      setIsVisible(false);
      setIsHiding(false);
      hideTimerRef.current = null;
    }, 100);
  }, []);

  // 检查评论区域（与 anheyu-pro checkCommentSection 一致，同时检查配置 + DOM）
  const checkCommentSection = useCallback(() => {
    const config = stateRef.current.siteConfig;
    const commentEnabled = config?.comment?.enable === true || config?.comment?.enable === "true";
    const commentElementExists = !!document.getElementById("post-comment");
    setHasCommentSection(commentEnabled && commentElementExists);
  }, []);

  // 调整菜单位置，避免超出窗口边界
  const adjustMenuPosition = useCallback((x: number, y: number) => {
    const menu = menuRef.current;
    if (!menu) return { x, y, origin: "top left" };

    const menuWidth = menu.offsetWidth || 200;
    const menuHeight = menu.offsetHeight || 300;
    const windowWidth = window.innerWidth;
    const windowHeight = window.innerHeight;

    let finalX = x;
    let finalY = y;
    let originX = "left";
    let originY = "top";

    if (x + menuWidth > windowWidth) {
      finalX = x - menuWidth;
      originX = "right";
    }

    if (y + menuHeight > windowHeight) {
      finalY = y - menuHeight;
      originY = "bottom";
    }

    finalX = Math.max(5, finalX);
    finalY = Math.max(5, finalY);

    return { x: finalX, y: finalY, origin: `${originY} ${originX}` };
  }, []);

  // 全局事件监听 - 注册一次，通过 ref 读取最新状态
  useEffect(() => {
    const handleContextMenu = (event: MouseEvent) => {
      const { useCustomContextMenu: enabled, pathname: path } = stateRef.current;
      if (!enabled) return;
      if (path.startsWith("/doc/")) return;
      if (window.innerWidth < 768) return;

      event.preventDefault();

      // 检查文本选中
      const selection = window.getSelection();
      const textSelected = selection ? !selection.isCollapsed : false;
      setIsTextSelected(textSelected);

      // 检查是否右键点击了音乐播放器
      const target = event.target as HTMLElement;
      const musicPlayer = target.closest("#nav-music");
      setIsClickOnMusicPlayer(!!musicPlayer);

      if (musicPlayer) {
        window.dispatchEvent(new CustomEvent("music-player-get-play-status"));
      }

      // 检查评论区域
      checkCommentSection();

      // 捕获选中文本
      if (textSelected && selection) {
        setCapturedText(selection.toString());

        const range = selection.rangeCount > 0 ? selection.getRangeAt(0) : null;
        if (range) {
          const container = range.commonAncestorContainer;
          const targetElement =
            container.nodeType === Node.TEXT_NODE ? container.parentElement : (container as HTMLElement);
          const postDetailContent = targetElement?.closest(".post-detail-content");
          setIsTextInPostDetail(!!postDetailContent);
        } else {
          setIsTextInPostDetail(false);
        }
      } else {
        setCapturedText("");
        setIsTextInPostDetail(false);
      }

      // 清除之前的隐藏动画
      if (hideTimerRef.current) {
        clearTimeout(hideTimerRef.current);
        hideTimerRef.current = null;
      }

      // 设置初始位置
      const clickX = event.clientX;
      const clickY = event.clientY;

      setPosition({ x: clickX, y: clickY });
      setIsVisible(true);
      setIsHiding(false);

      // 下一帧调整位置（确保 DOM 已渲染以获取实际尺寸）
      requestAnimationFrame(() => {
        const adjusted = adjustMenuPosition(clickX, clickY);
        setPosition({ x: adjusted.x, y: adjusted.y });
        setTransformOrigin(adjusted.origin);
      });
    };

    const handleClick = () => {
      if (isVisibleRef.current) hideMenu();
    };

    const handleScroll = () => {
      if (isVisibleRef.current) hideMenu();
    };

    const handleKeydown = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isVisibleRef.current) hideMenu();
    };

    const handlePlayStatus = (event: Event) => {
      const { isPlaying } = (event as CustomEvent).detail;
      setMusicIsPlaying(isPlaying);
    };

    const handleSongNameResponse = (event: Event) => {
      const { songName, artist } = (event as CustomEvent).detail;
      const fullName = artist ? `${artist} - ${songName}` : songName;
      safeClipboardWrite(fullName, "歌曲名称复制成功");
    };

    window.addEventListener("contextmenu", handleContextMenu);
    window.addEventListener("click", handleClick);
    window.addEventListener("scroll", handleScroll);
    window.addEventListener("keydown", handleKeydown);
    window.addEventListener("music-player-play-status-response", handlePlayStatus);
    window.addEventListener("music-player-song-name-response", handleSongNameResponse);

    return () => {
      window.removeEventListener("contextmenu", handleContextMenu);
      window.removeEventListener("click", handleClick);
      window.removeEventListener("scroll", handleScroll);
      window.removeEventListener("keydown", handleKeydown);
      window.removeEventListener("music-player-play-status-response", handlePlayStatus);
      window.removeEventListener("music-player-song-name-response", handleSongNameResponse);
      if (hideTimerRef.current) clearTimeout(hideTimerRef.current);
    };
  }, [hideMenu, checkCommentSection, adjustMenuPosition]);

  // 路由变化时重新检查评论区域（setTimeout 匹配 Vue nextTick，等 DOM 更新后再检查）
  useEffect(() => {
    const timer = setTimeout(checkCommentSection, 0);
    return () => clearTimeout(timer);
  }, [pathname, checkCommentSection]);

  // ===== 菜单项操作函数 =====
  const goBack = () => {
    window.history.back();
    hideMenu();
  };

  const goForward = () => {
    window.history.forward();
    hideMenu();
  };

  const refreshPage = () => {
    window.location.reload();
  };

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
    hideMenu();
  };

  const copySelectedText = () => {
    if (capturedText) {
      safeClipboardWrite(capturedText, "复制成功，复制和转载请标注本文地址");
    }
    hideMenu();
  };

  const quoteToComment = () => {
    if (capturedText) {
      window.dispatchEvent(new CustomEvent("quote-text-to-comment", { detail: { quoteText: capturedText } }));
      addToast({ title: "已引用到评论", color: "success", timeout: 2000 });
    }
    hideMenu();
  };

  const searchLocal = () => {
    if (capturedText) {
      window.dispatchEvent(new CustomEvent("frontend-open-search", { detail: { keyword: capturedText } }));
    }
    hideMenu();
  };

  const searchBaidu = () => {
    if (capturedText) {
      window.open(`https://www.baidu.com/s?wd=${encodeURIComponent(capturedText)}`, "_blank");
    }
    hideMenu();
  };

  const randomNavigate = () => {
    router.push("/random");
    hideMenu();
  };

  const gotoCategories = () => {
    router.push("/categories");
    hideMenu();
  };

  const gotoTags = () => {
    router.push("/tags");
    hideMenu();
  };

  const copyUrl = () => {
    safeClipboardWrite(window.location.href, "复制本页链接地址成功");
    hideMenu();
  };

  const toggleTheme = () => {
    setTheme(isDark ? "light" : "dark");
    hideMenu();
  };

  const handleToggleCommentBarrage = () => {
    toggleCommentBarrage();
    hideMenu();
  };

  // 音乐播放器控制
  const togglePlayPause = () => {
    window.dispatchEvent(new CustomEvent("music-player-toggle-play"));
    hideMenu();
  };

  const previousSong = () => {
    window.dispatchEvent(new CustomEvent("music-player-previous"));
    hideMenu();
  };

  const nextSong = () => {
    window.dispatchEvent(new CustomEvent("music-player-next"));
    hideMenu();
  };

  const copySongName = () => {
    window.dispatchEvent(new CustomEvent("music-player-get-song-name"));
    hideMenu();
  };

  // ===== 渲染 =====
  const menuClasses = [styles.rightMenu, isVisible ? styles.visible : "", isHiding ? styles.hiding : ""]
    .filter(Boolean)
    .join(" ");

  return (
    <div
      ref={menuRef}
      id="rightMenu"
      className={menuClasses}
      onClick={e => e.stopPropagation()}
      style={{
        top: `${position.y}px`,
        left: `${position.x}px`,
        transformOrigin,
      }}
    >
      {/* 导航栏 - 小图标行 */}
      <div className={`${styles.menuGroup} ${styles.menuSmall}`}>
        <div className={styles.menuItem} onClick={goBack}>
          <Icon icon="ri:arrow-left-s-line" />
        </div>
        <div className={styles.menuItem} onClick={goForward}>
          <Icon icon="ri:arrow-right-s-line" />
        </div>
        <div className={styles.menuItem} onClick={refreshPage}>
          <Icon icon="ri:refresh-line" style={{ fontSize: "0.9rem" }} />
        </div>
        <div className={styles.menuItem} onClick={scrollToTop}>
          <Icon icon="ri:arrow-up-line" />
        </div>
      </div>

      {/* 文本选中时的操作 */}
      {isTextSelected ? (
        <div className={`${styles.menuGroup} ${styles.menuGroupLine}`}>
          <div className={styles.menuItem} onClick={copySelectedText}>
            <Icon icon="ri:file-copy-line" />
            <span>复制选中文本</span>
          </div>
          {isTextInPostDetail && (
            <div className={styles.menuItem} onClick={quoteToComment}>
              <Icon icon="ri:chat-1-fill" />
              <span>引用到评论</span>
            </div>
          )}
          <div className={styles.menuItem} onClick={searchLocal}>
            <Icon icon="ri:search-line" />
            <span>站内搜索</span>
          </div>
          <div className={styles.menuItem} onClick={searchBaidu}>
            <Icon icon="ri:search-line" />
            <span>百度搜索</span>
          </div>
        </div>
      ) : (
        <div className={`${styles.menuGroup} ${styles.menuGroupLine}`}>
          <div className={styles.menuItem} onClick={randomNavigate}>
            <Icon icon="ri:shuffle-line" />
            <span>随便逛逛</span>
          </div>
          <div className={styles.menuItem} onClick={gotoCategories}>
            <Icon icon="ri:folder-line" />
            <span>博客分类</span>
          </div>
          <div className={styles.menuItem} onClick={gotoTags}>
            <Icon icon="ri:price-tag-3-line" />
            <span>文章标签</span>
          </div>
        </div>
      )}

      {/* 音乐播放器控制 - 仅在右键音乐播放器时显示 */}
      {isClickOnMusicPlayer && (
        <div className={`${styles.menuGroup} ${styles.menuGroupLine}`}>
          <div className={styles.menuItem} onClick={togglePlayPause}>
            <Icon icon={musicIsPlaying ? "ri:pause-fill" : "ri:play-fill"} />
            <span>{musicIsPlaying ? "暂停" : "播放"}</span>
          </div>
          <div className={styles.menuItem} onClick={previousSong}>
            <Icon icon="ri:skip-back-fill" />
            <span>上一首</span>
          </div>
          <div className={styles.menuItem} onClick={nextSong}>
            <Icon icon="ri:skip-forward-fill" />
            <span>下一首</span>
          </div>
          <div className={styles.menuItem} onClick={copySongName}>
            <Icon icon="ri:file-copy-line" />
            <span>复制歌名</span>
          </div>
        </div>
      )}

      {/* 通用操作 */}
      <div className={`${styles.menuGroup} ${styles.menuGroupLine}`}>
        <div className={styles.menuItem} onClick={copyUrl}>
          <Icon icon="ri:file-copy-line" />
          <span>复制地址</span>
        </div>
        <div className={styles.menuItem} onClick={toggleTheme}>
          <Icon icon="ri:contrast-2-line" />
          <span>{isDark ? "浅色模式" : "深色模式"}</span>
        </div>
        {hasCommentSection && (
          <div className={styles.menuItem} onClick={handleToggleCommentBarrage}>
            <Icon icon="ri:chat-3-line" />
            <span>{isCommentBarrageVisible ? "隐藏热评" : "显示热评"}</span>
          </div>
        )}
      </div>
    </div>
  );
}

// src/layout/frontend/components/RightMenu/index.vue
<template>
  <div v-show="isVisible" id="rightMenu" ref="rightMenuRef" :style="menuStyle">
    <div class="rightMenu-group rightMenu-small">
      <div class="rightMenu-item" @click.stop="goBack">
        <i class="anzhiyufont anzhiyu-icon-arrow-left" />
      </div>
      <div class="rightMenu-item" @click.stop="goForward">
        <i class="anzhiyufont anzhiyu-icon-arrow-right" />
      </div>
      <div class="rightMenu-item" @click.stop="refreshPage">
        <i
          class="anzhiyufont anzhiyu-icon-arrow-rotate-right"
          style="font-size: 0.9rem"
        />
      </div>
      <div class="rightMenu-item" @click.stop="scrollToTop">
        <i class="anzhiyufont anzhiyu-icon-arrow-up" />
      </div>
    </div>

    <div v-if="isTextSelected" class="rightMenu-group rightMenu-line">
      <div class="rightMenu-item" @click.stop="copySelectedText">
        <i class="anzhiyufont anzhiyu-icon-copy" />
        <span>复制选中文本</span>
      </div>
      <div
        v-if="isTextInPostDetailContent"
        class="rightMenu-item"
        @click.stop="quoteToComment"
      >
        <IconifyIconOffline icon="ri:chat-1-fill" />
        <span>引用到评论</span>
      </div>
      <div class="rightMenu-item" @click.stop="searchLocal">
        <i class="anzhiyufont anzhiyu-icon-magnifying-glass" />
        <span>站内搜索</span>
      </div>
      <div class="rightMenu-item" @click.stop="searchBaidu">
        <i class="anzhiyufont anzhiyu-icon-magnifying-glass" />
        <span>百度搜索</span>
      </div>
    </div>

    <div v-else class="rightMenu-group rightMenu-line">
      <a class="rightMenu-item menu-link" @click.stop="randomNavigate">
        <i class="anzhiyufont anzhiyu-icon-shuffle" />
        <span>随便逛逛</span>
      </a>
      <a class="rightMenu-item menu-link" @click.stop="gotoCategory">
        <i class="anzhiyufont anzhiyu-icon-cube" />
        <span>博客分类</span>
      </a>
      <a class="rightMenu-item menu-link" @click.stop="gotoTag">
        <i class="anzhiyufont anzhiyu-icon-tags" />
        <span>文章标签</span>
      </a>
    </div>

    <div v-if="isClickOnMusicPlayer" class="rightMenu-group rightMenu-line">
      <div class="rightMenu-item" @click.stop="togglePlayPause">
        <i
          class="anzhiyufont"
          :class="musicIsPlaying ? 'anzhiyu-icon-pause' : 'anzhiyu-icon-play'"
        />
        <span>{{ musicIsPlaying ? "暂停" : "播放" }}</span>
      </div>
      <div class="rightMenu-item" @click.stop="previousSong">
        <i class="anzhiyufont anzhiyu-icon-backward" />
        <span>上一首</span>
      </div>
      <div class="rightMenu-item" @click.stop="nextSong">
        <i class="anzhiyufont anzhiyu-icon-forward" />
        <span>下一首</span>
      </div>
      <div class="rightMenu-item" @click.stop="copySongName">
        <i class="anzhiyufont anzhiyu-icon-copy" />
        <span>复制歌名</span>
      </div>
    </div>

    <div class="rightMenu-group rightMenu-line">
      <div class="rightMenu-item" @click.stop="copyUrl">
        <i class="anzhiyufont anzhiyu-icon-copy" />
        <span> 复制地址 </span>
      </div>

      <div class="rightMenu-item" @click.stop="toggleTheme">
        <i class="anzhiyufont anzhiyu-icon-circle-half-stroke" />
        <span class="menu-darkmode-text">{{
          dataTheme ? "浅色模式" : "深色模式"
        }}</span>
      </div>

      <div
        v-if="hasCommentSection"
        class="rightMenu-item"
        @click.stop="handleToggleCommentBarrage"
      >
        <i class="anzhiyufont anzhiyu-icon-comments" />
        <span class="menu-commentBarrage-text">{{
          isCommentBarrageVisible ? "隐藏热评" : "显示热评"
        }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  ref,
  onMounted,
  onUnmounted,
  reactive,
  computed,
  nextTick,
  watch
} from "vue";
import { useRouter, useRoute } from "vue-router";
import { useArticleStore } from "@/store/modules/articleStore";
import { useCopyToClipboard } from "@pureadmin/utils";
import { useDataThemeChange } from "@/layout/hooks/useDataThemeChange";
import { useSnackbar } from "@/composables/useSnackbar";
import { useUiStore } from "@/store/modules/uiStore";
import { useSiteConfigStore } from "@/store/modules/siteConfig";
import { storeToRefs } from "pinia";
import gsap from "gsap";
import IconifyIconOffline from "@/components/ReIcon/src/iconifyIconOffline";

const rightMenuRef = ref<HTMLElement | null>(null);
const isVisible = ref(false);
const isTextSelected = ref(false);
const position = reactive({ x: 0, y: 0 });
const capturedText = ref("");
const hasCommentSection = ref(false);
const isClickOnMusicPlayer = ref(false);
const transformOrigin = ref("top left");
const musicIsPlaying = ref(false);
const isTextInPostDetailContent = ref(false);

const router = useRouter();
const route = useRoute();
const articleStore = useArticleStore();
const { copied, update } = useCopyToClipboard();
const { dataTheme, dataThemeChange } = useDataThemeChange();
const { showSnackbar } = useSnackbar();
const uiStore = useUiStore();
const siteConfigStore = useSiteConfigStore();

const { isCommentBarrageVisible, useCustomContextMenu } = storeToRefs(uiStore);
const { toggleCommentBarrage } = uiStore;

const menuStyle = computed(() => ({
  top: `${position.y}px`,
  left: `${position.x}px`,
  transformOrigin: transformOrigin.value
}));

const handleToggleCommentBarrage = () => {
  toggleCommentBarrage();
  hideMenu();
};

const handleContextMenu = (event: MouseEvent) => {
  // 如果关闭了本站右键菜单，则直接返回，显示浏览器原生菜单
  if (!useCustomContextMenu.value) {
    return;
  }

  // 仅在桌面端设备生效
  if (window.innerWidth < 768) return;

  event.preventDefault();

  const selection = window.getSelection();
  isTextSelected.value = selection ? !selection.isCollapsed : false;

  // 检查是否右键点击了音乐播放器
  const target = event.target as HTMLElement;
  const musicPlayer = target.closest("#nav-music");
  isClickOnMusicPlayer.value = !!musicPlayer;

  // 如果点击了音乐播放器，请求当前播放状态
  if (isClickOnMusicPlayer.value) {
    window.dispatchEvent(new CustomEvent("music-player-get-play-status"));
  }

  // 每次打开右键菜单时重新检查评论区域是否存在
  checkCommentSection();

  // 修改：在菜单显示时就捕获选中的文本
  if (isTextSelected.value && selection) {
    capturedText.value = selection.toString();

    // 检查选中的文本是否在 post-detail-content 中
    const range = selection.rangeCount > 0 ? selection.getRangeAt(0) : null;
    if (range) {
      const container = range.commonAncestorContainer;
      const targetElement =
        container.nodeType === Node.TEXT_NODE
          ? container.parentElement
          : (container as HTMLElement);

      // 检查是否在 post-detail-content 中
      const postDetailContent = targetElement?.closest(".post-detail-content");
      isTextInPostDetailContent.value = !!postDetailContent;
    } else {
      isTextInPostDetailContent.value = false;
    }
  } else {
    capturedText.value = "";
    isTextInPostDetailContent.value = false;
  }

  // 初始设置菜单位置
  position.x = event.clientX;
  position.y = event.clientY;
  isVisible.value = true;

  nextTick(() => {
    // 调整菜单位置以避免超出窗口边界
    adjustMenuPosition();

    // GSAP 动画
    gsap.fromTo(
      rightMenuRef.value,
      { scale: 0.9, opacity: 0, y: -10 },
      {
        scale: 1,
        opacity: 1,
        y: 0,
        duration: 0.2,
        ease: "power2.out"
      }
    );
  });
};

/**
 * 检查页面是否存在评论区域
 * 同时检查评论功能是否启用
 */
const checkCommentSection = () => {
  const commentEnabled =
    siteConfigStore.getSiteConfig?.comment?.enable === true;
  const commentElementExists = !!document.getElementById("post-comment");
  hasCommentSection.value = commentEnabled && commentElementExists;
};

/**
 * 调整菜单位置以避免超出窗口边界，并计算动画起点
 */
const adjustMenuPosition = () => {
  if (!rightMenuRef.value) return;

  const menu = rightMenuRef.value;
  const menuRect = menu.getBoundingClientRect();
  const windowWidth = window.innerWidth;
  const windowHeight = window.innerHeight;

  // 获取菜单的实际尺寸
  const menuWidth = menuRect.width;
  const menuHeight = menuRect.height;

  // 保存原始点击位置
  const initialX = position.x;
  const initialY = position.y;

  // 计算最终位置和动画起点
  let finalX = initialX;
  let finalY = initialY;
  let originX = "left";
  let originY = "top";

  // 水平边界检测和调整
  if (initialX + menuWidth > windowWidth) {
    finalX = initialX - menuWidth;
    originX = "right";
  }

  // 垂直边界检测和调整
  if (initialY + menuHeight > windowHeight) {
    finalY = initialY - menuHeight;
    originY = "bottom";
  }

  // 确保菜单不会超出屏幕边缘（留出5px边距）
  finalX = finalX < 5 ? 5 : finalX;
  finalY = finalY < 5 ? 5 : finalY;

  // 应用最终位置
  position.x = finalX;
  position.y = finalY;

  // 设置动画起点
  transformOrigin.value = `${originY} ${originX}`;

  console.log(
    `菜单位置调整: 点击(${initialX}, ${initialY}) -> 最终(${finalX}, ${finalY}), 动画起点: ${transformOrigin.value}`
  );
};

const hideMenu = () => {
  if (isVisible.value) {
    gsap.to(rightMenuRef.value, {
      scale: 0.9,
      opacity: 0,
      duration: 0.1,
      ease: "power1.in",
      onComplete: () => {
        isVisible.value = false;
      }
    });
  }
};

const handleKeydown = (event: KeyboardEvent) => {
  if (event.key === "Escape") {
    hideMenu();
  }
};

const gotoCategory = () => {
  router.push("/categories");
  hideMenu();
};

const gotoTag = () => {
  router.push("/tags");
  hideMenu();
};

const goBack = () => {
  window.history.back();
  hideMenu();
};

const goForward = () => {
  window.history.forward();
  hideMenu();
};

const refreshPage = () => {
  window.location.reload();
  hideMenu();
};

const scrollToTop = () => {
  window.scrollTo({ top: 0, behavior: "smooth" });
  hideMenu();
};

const copySelectedText = () => {
  // 修改：直接使用暂存的文本
  const text = capturedText.value;
  if (text) {
    update(text);
    if (copied.value) {
      showSnackbar("复制成功，复制和转载请标注本文地址");
    }
  }
  hideMenu();
};

const searchBaidu = () => {
  const text = capturedText.value;
  if (text) {
    window.open(
      `https://www.baidu.com/s?wd=${encodeURIComponent(text)}`,
      "_blank"
    );
  }
  hideMenu();
};

const searchLocal = () => {
  const text = capturedText.value;
  if (text) {
    window.dispatchEvent(
      new CustomEvent("frontend-open-search", { detail: { keyword: text } })
    );
  }
  hideMenu();
};

/**
 * 引用到评论
 */
const quoteToComment = () => {
  const text = capturedText.value;
  if (text) {
    // 通过全局事件通知文章详情页
    window.dispatchEvent(
      new CustomEvent("quote-text-to-comment", { detail: { quoteText: text } })
    );
    showSnackbar("已引用到评论");
  }
  hideMenu();
};

const randomNavigate = () => {
  articleStore.navigateToRandomArticle();
  hideMenu();
};

const toggleTheme = () => {
  dataThemeChange(dataTheme.value ? "light" : "dark");
  hideMenu();
};

const copyUrl = () => {
  const url = window.location.href;
  update(url);
  if (copied.value) {
    showSnackbar("复制本页链接地址成功");
  }
  hideMenu();
};

// 音乐播放器控制函数
const togglePlayPause = () => {
  // 通过全局事件控制播放/暂停
  window.dispatchEvent(new CustomEvent("music-player-toggle-play"));
  hideMenu();
};

const previousSong = () => {
  // 通过全局事件与音乐播放器通信
  window.dispatchEvent(new CustomEvent("music-player-previous"));
  hideMenu();
};

const nextSong = () => {
  // 通过全局事件与音乐播放器通信
  window.dispatchEvent(new CustomEvent("music-player-next"));
  hideMenu();
};

const copySongName = () => {
  // 通过全局事件请求歌曲名称
  window.dispatchEvent(new CustomEvent("music-player-get-song-name"));
  hideMenu();
};

// 处理音乐播放器歌曲名称响应
const handleSongNameResponse = (event: CustomEvent) => {
  const { songName, artist } = event.detail;
  const fullName = artist ? `${artist} - ${songName}` : songName;

  update(fullName);
  if (copied.value) {
    showSnackbar("歌曲名称复制成功");
  }
};

// 处理音乐播放状态响应
const handleMusicPlayStatusResponse = (event: CustomEvent) => {
  const { isPlaying } = event.detail;
  musicIsPlaying.value = isPlaying;
};

onMounted(() => {
  window.addEventListener("contextmenu", handleContextMenu);
  window.addEventListener("click", hideMenu);
  window.addEventListener("keydown", handleKeydown);
  window.addEventListener("scroll", hideMenu);
  window.addEventListener(
    "music-player-song-name-response",
    handleSongNameResponse as EventListener
  );
  window.addEventListener(
    "music-player-play-status-response",
    handleMusicPlayStatusResponse as EventListener
  );

  // 初始检查评论区域
  checkCommentSection();
});

// 监听路由变化，重新检查评论区域
watch(
  () => route.path,
  () => {
    nextTick(() => {
      checkCommentSection();
    });
  }
);

onUnmounted(() => {
  window.removeEventListener("contextmenu", handleContextMenu);
  window.removeEventListener("click", hideMenu);
  window.removeEventListener("keydown", handleKeydown);
  window.removeEventListener("scroll", hideMenu);
  window.removeEventListener(
    "music-player-song-name-response",
    handleSongNameResponse as EventListener
  );
  window.removeEventListener(
    "music-player-play-status-response",
    handleMusicPlayStatusResponse as EventListener
  );
});
</script>

<style scoped lang="scss">
#rightMenu {
  position: fixed;
  z-index: 9999;
  padding: 8px;
  font-size: 14px;
  color: var(--anzhiyu-fontcolor);
  background-color: var(--anzhiyu-maskbg);
  backdrop-filter: blur(20px);
  backdrop-filter: saturate(180%) blur(20px);
  border: var(--style-border);
  border-radius: 12px;
  box-shadow: var(--anzhiyu-shadow-contextmenu);
  opacity: 0;

  /* transform-origin 现在通过 JavaScript 动态设置 */
}

.rightMenu-group {
  display: flex;
  gap: 4px;
  align-items: center;

  &:not(:last-child) {
    margin-bottom: 4px;
  }

  &.rightMenu-line {
    flex-direction: column;
    padding-top: 4px;
    border-top: 2px dashed var(--anzhiyu-theme-op);
  }
}

.rightMenu-item {
  display: flex;
  align-items: center;
  width: 100%;
  padding: 6px 10px;
  white-space: nowrap;
  cursor: pointer;
  border-radius: 8px;
  transition:
    background-color 0.2s ease,
    color 0.2s ease;

  i,
  svg {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 1em;
    height: 1em;
    margin-right: 8px;
    font-size: 1rem;
  }
  svg {
    margin-right: 5px;
  }

  &:hover {
    color: var(--anzhiyu-white);
    background-color: var(--anzhiyu-main);
  }
}

.rightMenu-small .rightMenu-item {
  justify-content: center;
  width: 32px;
  height: 32px;
  padding: 0;

  i,
  svg {
    margin-right: 0;
  }
}
</style>
