// src/views/post/link/components/LinkListSection.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from "vue";
import { useLinkStore } from "@/store/modules/link";
import SiteCardGroup from "./SiteCardGroup.vue";
import FlinkList from "./FlinkList.vue";

defineOptions({
  name: "LinkListSection"
});

const linkStore = useLinkStore();

const handleScroll = () => {
  const scrollHeight = document.documentElement.scrollHeight;
  const scrollTop = document.documentElement.scrollTop;
  const clientHeight = document.documentElement.clientHeight;

  if (scrollTop + clientHeight >= scrollHeight - 200) {
    for (const category of linkStore.categories) {
      const state = linkStore.linksByCategory[category.id];
      if (state && !state.finished && !state.loading) {
        linkStore.fetchLinksForCategory(category.id);
        break;
      }
    }
  }
};

onMounted(async () => {
  await linkStore.fetchCategories();
  if (linkStore.categories.length > 0) {
    linkStore.fetchLinksForCategory(linkStore.categories[0].id);
  }
  window.addEventListener("scroll", handleScroll);
});

onUnmounted(() => {
  window.removeEventListener("scroll", handleScroll);
});
</script>

<template>
  <div id="article-container" class="flink">
    <div
      v-for="category in linkStore.categories"
      :key="category.id"
      class="link-group"
    >
      <div class="power_title_bar">
        <h2 :id="category.name">
          <a :href="`#${category.name}`" class="headerlink">{{
            category.name +
            " " +
            "(" +
            (linkStore.linksByCategory[category.id]?.total || 0) +
            ")"
          }}</a>
        </h2>
        <div class="flink-desc">
          {{ category?.description }}
        </div>
      </div>
      <SiteCardGroup
        v-if="category.style === 'card'"
        :links="linkStore.linksByCategory[category.id]?.list || []"
      />
      <FlinkList
        v-else
        :links="linkStore.linksByCategory[category.id]?.list || []"
      />
      <div
        v-if="linkStore.linksByCategory[category.id]?.loading"
        class="loading-tip"
      >
        正在加载...
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.link-group {
  margin-top: 30px;
}
.power_title_bar {
  margin-bottom: 20px;
  h2 {
    font-size: 1.5rem;
    margin: 0;
    .headerlink {
      text-decoration: none;
      color: var(--anzhiyu-fontcolor);
    }
    span {
      font-size: 1.2rem;
      color: var(--anzhiyu-second-fontcolor);
    }
  }
  .flink-desc {
    color: var(--anzhiyu-secondtext);
    margin: 0px;
  }
}
.loading-tip {
  text-align: center;
  color: var(--anzhiyu-second-fontcolor);
  padding: 20px 0;
}
</style>

// src/app/(frontend)/link/_components/LinkListSection.tsx
"use client";

import { usePublicCategories, usePublicLinks } from "@/hooks/queries/use-friends";
import { Loader2 } from "lucide-react";
import { SiteCardGroup } from "./SiteCardGroup";
import { FlinkList } from "./FlinkList";
import type { LinkCategory } from "@/types/friends";

function CategorySection({ category }: { category: LinkCategory }) {
  const { data, isPending } = usePublicLinks({ category_id: category.id, pageSize: 200 });
  const links = data?.list || [];
  const total = data?.total || 0;

  return (
    <div className="link-group" data-category-id={category.id}>
      <div className="power_title_bar">
        <h2 id={category.name}>
          <a href={`#${category.name}`} className="headerlink">
            {category.name} ({total})
          </a>
        </h2>
        {category.description && <div className="flink-desc">{category.description}</div>}
      </div>

      {category.style === "card" ? <SiteCardGroup links={links} /> : <FlinkList links={links} />}

      {isPending && (
        <div className="loading-tip">
          <Loader2 className="w-4 h-4 animate-spin inline mr-2" />
          正在加载...
        </div>
      )}
    </div>
  );
}

export function LinkListSection() {
  const { data: categories, isPending, isError } = usePublicCategories();

  if (isPending) {
    return (
      <div className="loading-tip" style={{ padding: "40px 0" }}>
        <Loader2 className="w-5 h-5 animate-spin inline mr-2" />
        加载中...
      </div>
    );
  }

  if (isError) {
    return (
      <p className="text-sm" style={{ color: "var(--anzhiyu-secondtext)" }}>
        加载友链分类失败，请稍后再试。
      </p>
    );
  }

  if (!categories || categories.length === 0) {
    return (
      <p className="text-sm" style={{ color: "var(--anzhiyu-secondtext)" }}>
        暂无友链分类
      </p>
    );
  }

  return (
    <div id="article-container" className="flink">
      {categories.map(category => (
        <CategorySection key={category.id} category={category} />
      ))}
    </div>
  );
}
