// src/views/system/file-management/components/FileBreadcrumb.vue
<template>
  <div class="file-breadcrumb-wrapper" @click="switchToEditMode">
    <div v-if="!isEditing" class="file-breadcrumb">
      <el-tooltip content="返回根目录" placement="bottom">
        <el-icon class="home-icon" @click.stop="onNavigate('/')"
          ><HomeFilled
        /></el-icon>
      </el-tooltip>
      <el-breadcrumb :separator-icon="ArrowRight">
        <el-breadcrumb-item
          v-for="(segment, index) in pathSegments"
          :key="segment.path"
        >
          <!-- 最后一个 segment 且需要显示下拉菜单时 -->
          <el-dropdown
            v-if="isLastSegment(index) && showDropdown"
            trigger="click"
            placement="bottom-start"
            @command="handleCommand"
            @visible-change="isDropdownVisible = $event"
          >
            <span class="el-dropdown-link" @click.stop>
              {{ segment.name }}
              <IconifyIconOnline
                icon="raphael:arrowdown"
                class="el-icon--right"
              />
            </span>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item :command="{ action: 'enter' }">
                  <IconifyIconOffline :icon="Back" class="dropdown-icon" />进入
                </el-dropdown-item>
                <el-dropdown-item :command="{ action: 'download' }">
                  <IconifyIconOffline
                    :icon="Download"
                    class="dropdown-icon"
                  />下载
                </el-dropdown-item>
                <el-dropdown-item :command="{ action: 'share' }">
                  <IconifyIconOffline :icon="Share" class="dropdown-icon" />分享
                </el-dropdown-item>
                <el-dropdown-item :command="{ action: 'rename' }">
                  <IconifyIconOffline
                    :icon="EditPen"
                    class="dropdown-icon"
                  />重命名
                </el-dropdown-item>
                <el-dropdown-item :command="{ action: 'copy' }">
                  <IconifyIconOffline
                    :icon="CopyDocument"
                    class="dropdown-icon"
                  />复制
                </el-dropdown-item>
                <el-dropdown-item :command="{ action: 'link' }">
                  <IconifyIconOffline
                    :icon="Link"
                    class="dropdown-icon"
                  />获取直链
                </el-dropdown-item>
                <el-dropdown-item :command="{ action: 'tags' }" divided>
                  <IconifyIconOffline
                    :icon="PriceTag"
                    class="dropdown-icon"
                  />标签
                </el-dropdown-item>
                <el-dropdown-item :command="{ action: 'organize' }">
                  <IconifyIconOffline
                    :icon="FolderOpened"
                    class="dropdown-icon"
                  />整理
                </el-dropdown-item>
                <el-dropdown-item :command="{ action: 'more' }">
                  <IconifyIconOffline
                    :icon="Setting"
                    class="dropdown-icon"
                  />更多操作
                </el-dropdown-item>
                <el-dropdown-item :command="{ action: 'info' }" divided>
                  <IconifyIconOffline
                    :icon="InfoFilled"
                    class="dropdown-icon"
                  />详细信息
                </el-dropdown-item>
                <el-dropdown-item
                  :command="{ action: 'delete' }"
                  class="danger-item"
                >
                  <IconifyIconOffline
                    :icon="Delete"
                    class="dropdown-icon"
                  />删除
                </el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>

          <!-- 其他情况，作为普通链接 -->
          <span v-else class="is-link" @click.stop="onNavigate(segment.path)">
            {{ segment.name }}
          </span>
        </el-breadcrumb-item>
      </el-breadcrumb>
    </div>

    <div v-else class="input-mode">
      <el-tooltip content="返回根目录" placement="bottom">
        <el-icon class="home-icon" @click.stop="onNavigate('/')"
          ><HomeFilled
        /></el-icon>
      </el-tooltip>
      <el-input
        ref="pathInputRef"
        v-model="pathInput"
        placeholder="请输入绝对路径后按 Enter"
        @blur="handleSubmit"
        @keydown.enter.prevent="handleSubmit"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, nextTick, watch } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { extractLogicalPathFromUri } from "@/utils/fileUtils";

import { HomeFilled, ArrowRight } from "@element-plus/icons-vue";
import Back from "@iconify-icons/ep/back";
import Download from "@iconify-icons/ep/download";
import Share from "@iconify-icons/ep/share";
import EditPen from "@iconify-icons/ep/edit-pen";
import CopyDocument from "@iconify-icons/ep/copy-document";
import Link from "@iconify-icons/ep/link";
import PriceTag from "@iconify-icons/ep/price-tag";
import FolderOpened from "@iconify-icons/ep/folder-opened";
import Setting from "@iconify-icons/ep/setting";
import InfoFilled from "@iconify-icons/ep/info-filled";
import Delete from "@iconify-icons/ep/delete";

const props = defineProps<{
  path: string;
  parentInfo?: { id: string; name: string } | null;
  showDropdown?: boolean;
}>();

const emit = defineEmits<{
  (e: "navigate", path: string): void;
  (e: "show-details", id: string): void;
  (e: "download-folder", id: string): void;
}>();

const isEditing = ref(false);
const pathInput = ref(props.path);
const pathInputRef = ref<HTMLInputElement | null>(null);
const isDropdownVisible = ref(false);

const pathSegments = computed(() => {
  const logicalPath = extractLogicalPathFromUri(props.path || "/");

  if (logicalPath === "/") {
    return [{ name: "我的文件", path: "/" }];
  }

  const segments = logicalPath.split("/").filter(Boolean);
  const result = [{ name: "我的文件", path: "/" }];
  let cumulativePath = "";
  for (const segment of segments) {
    cumulativePath += `/${segment}`;
    result.push({ name: segment, path: cumulativePath });
  }

  return result;
});

const isLastSegment = (index: number) => {
  return (
    index === pathSegments.value.length - 1 && pathSegments.value.length > 1
  );
};

const onNavigate = (newPath: string) => {
  const logicalPath = extractLogicalPathFromUri(newPath);
  if (logicalPath === props.path && logicalPath !== "/") return;
  emit("navigate", logicalPath);
};

const switchToEditMode = () => {
  if (isDropdownVisible.value) return;
  isEditing.value = true;
  nextTick(() => {
    pathInputRef.value?.focus();
  });
};

const handleSubmit = () => {
  let finalPath = pathInput.value.trim();
  // 使用工具函数确保是逻辑路径
  finalPath = extractLogicalPathFromUri(finalPath);
  // 规范化路径，移除末尾斜杠
  if (finalPath.length > 1 && finalPath.endsWith("/")) {
    finalPath = finalPath.slice(0, -1);
  }
  if (!finalPath.startsWith("/")) {
    finalPath = `/${finalPath}`;
  }

  isEditing.value = false;
  if (finalPath === props.path) return;
  onNavigate(finalPath);
};

interface CommandPayload {
  action: string;
}

const handleCommand = (command: CommandPayload) => {
  const { action } = command;
  if (!props.parentInfo?.id) {
    ElMessage.warning("无法获取当前目录信息");
    return;
  }

  switch (action) {
    case "enter":
      onNavigate(props.path);
      break;
    case "info":
      emit("show-details", props.parentInfo.id);
      break;
    case "download":
      emit("download-folder", props.parentInfo.id);
      break;
    case "delete":
      ElMessageBox.confirm(
        `确定要删除文件夹 "${props.parentInfo.name}" 吗？此操作不可恢复。`,
        "警告",
        {
          confirmButtonText: "确定删除",
          cancelButtonText: "取消",
          type: "warning"
        }
      )
        .then(() => {
          ElMessage.info("删除操作应由父组件处理");
        })
        .catch(() => ElMessage.info("已取消删除"));
      break;
    default:
      ElMessage.info(`功能 [${action}] 正在开发中...`);
      break;
  }
};

watch(
  () => props.path,
  newPath => {
    pathInput.value = extractLogicalPathFromUri(newPath);
  },
  { immediate: true }
);
</script>

<style scoped lang="scss">
.dropdown-icon {
  margin-right: 8px;
}

:root {
  --style-border: 1px solid #e0e0e0;
}

.file-breadcrumb-wrapper {
  display: flex;
  align-items: center;
  min-height: 52px;
  padding: 0 24px;
  overflow: hidden;
  cursor: text;
  background-color: var(--anzhiyu-card-bg);
  border: var(--style-border);
  border-radius: 12px;
}

.file-breadcrumb {
  display: flex;
  align-items: center;
  width: 100%;
}

.home-icon {
  margin-right: 12px;
  font-size: 16px;
  color: var(--anzhiyu-fontcolor);
  cursor: pointer;
}

.home-icon:hover {
  color: var(--el-color-primary);
}

.is-link {
  display: inline-block;
  padding: 8px;
  font-weight: normal;
  cursor: pointer;
  border-radius: 4px;
  transition: background-color 0.2s;
}

.is-link:hover {
  color: var(--el-color-primary);
  background-color: #f5f7fa;
}

.el-breadcrumb__item:not(:last-child) .is-link {
  font-weight: normal;
  color: var(--anzhiyu-fontcolor);
}

.el-breadcrumb__item:first-child .is-link {
  color: var(--anzhiyu-fontcolor);
}

.el-dropdown-link {
  display: flex;
  align-items: center;
  padding: 8px;
  font-weight: 600;
  color: #303133;
  cursor: pointer;
  border-radius: 4px;
  transition: background-color 0.2s;
}

.el-dropdown-link .el-icon--right {
  display: inline-flex;
  align-items: center;
  margin-left: 5px;
  font-size: 12px;
}

.danger-item {
  color: var(--el-color-error);
}

.danger-item:hover {
  color: var(--anzhiyu-card-bg) !important;
  background-color: var(--el-color-error) !important;
}

.danger-item .dropdown-icon {
  color: var(--el-color-error);
}

.danger-item:hover .dropdown-icon {
  color: var(--anzhiyu-card-bg) !important;
}

.el-dropdown-link:hover {
  background-color: #f5f7fa !important;
}

.input-mode {
  display: flex;
  align-items: center;
  width: 100%;

  :deep(.el-input__wrapper) {
    padding: 4px !important;
    box-shadow: none !important;

    &:hover {
      box-shadow: none !important;
    }
  }
}
</style>

// src/components/admin/file-manager/FileBreadcrumb.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  RiArrowDownSLine,
  RiArrowRightSLine,
  RiDeleteBin6Line,
  RiDownload2Line,
  RiEdit2Line,
  RiFileCopyLine,
  RiFolderOpenLine,
  RiFolderSettingsLine,
  RiHome2Line,
  RiInformationLine,
  RiLinkM,
  RiMore2Line,
  RiPriceTag3Line,
  RiShareLine,
} from "react-icons/ri";
import { addToast } from "@heroui/react";
import { extractLogicalPathFromUri } from "@/utils/file-manager";
import { Tooltip } from "@/components/ui/tooltip";
import { springTransition, contextMenuVariants, menuItemVariants } from "@/lib/motion";
import styles from "./FileBreadcrumb.module.css";

interface FileBreadcrumbProps {
  path: string;
  parentInfo?: { id: string; name: string } | null;
  showDropdown?: boolean;
  onNavigate: (path: string) => void;
  onShowDetails: (id: string) => void;
  onDownloadFolder: (id: string) => void;
  onDeleteFolder?: (id: string) => void;
}

export function FileBreadcrumb({
  path,
  parentInfo,
  showDropdown = true,
  onNavigate,
  onShowDetails,
  onDownloadFolder,
  onDeleteFolder,
}: FileBreadcrumbProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [pathInput, setPathInput] = useState(path);
  const [dropdownVisible, setDropdownVisible] = useState(false);
  const dropdownRef = useRef<HTMLDivElement | null>(null);
  const inputRef = useRef<HTMLInputElement | null>(null);
  const toast = (title: string, color: "success" | "warning" | "danger" | "default" = "default") =>
    addToast({ title, color, timeout: 3000 });
  const actionLabels = new Map([
    ["share", "分享"],
    ["rename", "重命名"],
    ["copy", "复制"],
    ["link", "获取直链"],
    ["tags", "标签"],
    ["organize", "整理"],
    ["more", "更多操作"],
  ]);

  useEffect(() => {
    setPathInput(path);
  }, [path]);

  useEffect(() => {
    if (!dropdownVisible) return;
    const onClick = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setDropdownVisible(false);
      }
    };
    window.addEventListener("click", onClick);
    return () => window.removeEventListener("click", onClick);
  }, [dropdownVisible]);

  const pathSegments = useMemo(() => {
    const logicalPath = extractLogicalPathFromUri(path || "/");
    if (logicalPath === "/") {
      return [{ name: "我的文件", path: "/" }];
    }
    const segments = logicalPath.split("/").filter(Boolean);
    const result = [{ name: "我的文件", path: "/" }];
    let cumulativePath = "";
    for (const segment of segments) {
      cumulativePath += `/${segment}`;
      result.push({ name: segment, path: cumulativePath });
    }
    return result;
  }, [path]);

  const handleNavigate = (target: string) => {
    const logicalPath = extractLogicalPathFromUri(target);
    if (logicalPath === path && logicalPath !== "/") return;
    onNavigate(logicalPath);
  };

  const handleSubmit = () => {
    let finalPath = pathInput.trim();
    finalPath = extractLogicalPathFromUri(finalPath);
    if (finalPath.length > 1 && finalPath.endsWith("/")) {
      finalPath = finalPath.slice(0, -1);
    }
    if (!finalPath.startsWith("/")) {
      finalPath = `/${finalPath}`;
    }
    setIsEditing(false);
    if (finalPath === path) return;
    handleNavigate(finalPath);
  };

  const handleSwitchToEditMode = () => {
    if (dropdownVisible) return;
    setIsEditing(true);
    setTimeout(() => inputRef.current?.focus(), 0);
  };

  const handleDropdownAction = (action: string) => {
    const parentId = parentInfo?.id;
    switch (action) {
      case "enter":
        handleNavigate(path);
        break;
      case "download":
        if (!parentId) {
          toast("无法获取当前目录信息", "warning");
          break;
        }
        onDownloadFolder(parentId);
        break;
      case "info":
        if (!parentId) {
          toast("无法获取当前目录信息", "warning");
          break;
        }
        onShowDetails(parentId);
        break;
      case "delete":
        if (!parentId) {
          toast("无法获取当前目录信息", "warning");
          break;
        }
        if (onDeleteFolder) {
          onDeleteFolder(parentId);
        } else {
          toast("删除操作应由父组件处理", "warning");
        }
        break;
      case "share":
      case "rename":
      case "copy":
      case "link":
      case "tags":
      case "organize":
      case "more":
        toast(`功能「${actionLabels.get(action) ?? action}」正在开发中`, "default");
        break;
      default:
        break;
    }
    setDropdownVisible(false);
  };

  const dropdownItems = [
    { key: "enter", label: "进入", icon: <RiFolderOpenLine /> },
    { key: "download", label: "下载", icon: <RiDownload2Line /> },
    { key: "share", label: "分享", icon: <RiShareLine /> },
    { key: "rename", label: "重命名", icon: <RiEdit2Line /> },
    { key: "copy", label: "复制", icon: <RiFileCopyLine /> },
    { key: "link", label: "获取直链", icon: <RiLinkM /> },
    { key: "tags", label: "标签", icon: <RiPriceTag3Line />, divider: true },
    { key: "organize", label: "整理", icon: <RiFolderSettingsLine /> },
    { key: "more", label: "更多操作", icon: <RiMore2Line /> },
    { key: "info", label: "详细信息", icon: <RiInformationLine />, divider: true },
    { key: "delete", label: "删除", icon: <RiDeleteBin6Line />, danger: true },
  ];

  return (
    <div className={styles["file-breadcrumb-wrapper"]} onClick={handleSwitchToEditMode}>
      <AnimatePresence mode="wait">
        {isEditing ? (
          <motion.div
            key="input-mode"
            className={styles["input-mode"]}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
          >
            <Tooltip content="返回根目录" placement="bottom" showArrow={false}>
              <RiHome2Line
                className={styles["home-icon"]}
                onClick={event => {
                  event.stopPropagation();
                  handleNavigate("/");
                }}
              />
            </Tooltip>
            <input
              ref={inputRef}
              className={styles["path-input"]}
              value={pathInput}
              onChange={event => setPathInput(event.target.value)}
              placeholder="请输入绝对路径后按 Enter"
              onBlur={handleSubmit}
              onKeyDown={event => {
                if (event.key === "Enter") {
                  event.preventDefault();
                  handleSubmit();
                }
              }}
            />
          </motion.div>
        ) : (
          <motion.div
            key="breadcrumb-mode"
            className={styles["file-breadcrumb"]}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
          >
            <Tooltip content="返回根目录" placement="bottom" showArrow={false}>
              <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
                <RiHome2Line
                  className={styles["home-icon"]}
                  onClick={event => {
                    event.stopPropagation();
                    handleNavigate("/");
                  }}
                />
              </motion.div>
            </Tooltip>
            <div className={styles["breadcrumb-list"]}>
              <AnimatePresence mode="popLayout">
                {pathSegments.map((segment, index) => {
                  const isLast = index === pathSegments.length - 1 && pathSegments.length > 1;
                  return (
                    <motion.div
                      key={segment.path}
                      className={styles["breadcrumb-item"]}
                      initial={{ opacity: 0, x: 12 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: -12 }}
                      transition={springTransition}
                      layout
                    >
                      {isLast && showDropdown ? (
                        <div
                          className={styles["dropdown-trigger"]}
                          onClick={event => {
                            event.stopPropagation();
                            setDropdownVisible(!dropdownVisible);
                          }}
                          ref={dropdownRef}
                        >
                          <span>{segment.name}</span>
                          <motion.span animate={{ rotate: dropdownVisible ? 180 : 0 }} transition={{ duration: 0.2 }}>
                            <RiArrowDownSLine />
                          </motion.span>
                          <AnimatePresence>
                            {dropdownVisible ? (
                              <motion.div
                                className={styles["dropdown-menu"]}
                                variants={contextMenuVariants}
                                initial="initial"
                                animate="animate"
                                exit="exit"
                                transition={springTransition}
                              >
                                {dropdownItems.map((item, itemIndex) => (
                                  <motion.div
                                    key={item.key}
                                    variants={menuItemVariants}
                                    initial="initial"
                                    animate="animate"
                                    exit="exit"
                                    transition={{ ...springTransition, delay: itemIndex * 0.02 }}
                                    className={`${styles["dropdown-item"]} ${item.divider ? styles.divider : ""} ${
                                      item.danger ? styles["dropdown-danger"] : ""
                                    }`}
                                    onClick={() => handleDropdownAction(item.key)}
                                  >
                                    <span className={styles["dropdown-icon"]}>{item.icon}</span>
                                    <span>{item.label}</span>
                                  </motion.div>
                                ))}
                              </motion.div>
                            ) : null}
                          </AnimatePresence>
                        </div>
                      ) : (
                        <span
                          className={styles["breadcrumb-link"]}
                          onClick={event => {
                            event.stopPropagation();
                            handleNavigate(segment.path);
                          }}
                        >
                          {segment.name}
                        </span>
                      )}
                      {index < pathSegments.length - 1 ? (
                        <RiArrowRightSLine className={styles["breadcrumb-separator"]} />
                      ) : null}
                    </motion.div>
                  );
                })}
              </AnimatePresence>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
