// src/components/admin/settings/FloatingSaveButton.tsx
/*
 * @Author: 安知鱼
 * @Date: 2026-02-11 10:34:32
 * @Description:
 * @LastEditTime: 2026-02-12 12:07:46
 * @LastEditors: 安知鱼
 */
"use client";

import { useEffect, useMemo, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Save } from "lucide-react";
import { Button } from "@/components/ui";

interface FloatingSaveButtonProps {
  hasChanges: boolean;
  loading?: boolean;
  onSave: () => void;
}

export function FloatingSaveButton({ hasChanges, loading, onSave }: FloatingSaveButtonProps) {
  const isMac = useMemo(() => typeof navigator !== "undefined" && navigator.platform.toUpperCase().includes("MAC"), []);

  const handleSave = useCallback(() => {
    if (hasChanges && !loading) {
      onSave();
    }
  }, [hasChanges, loading, onSave]);

  // 监听 Cmd/Ctrl + S 快捷键
  useEffect(() => {
    const handleKeydown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "s") {
        e.preventDefault();
        handleSave();
      }
    };
    window.addEventListener("keydown", handleKeydown);
    return () => window.removeEventListener("keydown", handleKeydown);
  }, [handleSave]);

  return (
    <AnimatePresence>
      {hasChanges && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 20 }}
          transition={{ duration: 0.3, ease: [0.4, 0, 0.2, 1] }}
          className="fixed bottom-6 right-6 z-50 flex items-center gap-4 px-5 py-3 bg-background/90 backdrop-blur-lg rounded-full shadow-sm border border-default-200/60 max-md:bottom-4 max-md:right-4 max-md:left-4 max-md:gap-3 max-md:px-4 max-md:rounded-xl max-sm:bottom-3 max-sm:right-3 max-sm:left-3"
        >
          {/* 保存内容 */}
          <div className="flex items-center gap-3 flex-1">
            <span className="text-sm text-default-500 whitespace-nowrap">有未保存的更改</span>
            <Button size="sm" disabled={loading} onClick={onSave} className="gap-1.5 shadow-lg shadow-primary/20">
              {loading ? (
                <span className="w-3.5 h-3.5 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
              ) : (
                <Save className="w-3.5 h-3.5" />
              )}
              {loading ? "保存中..." : "保存设置"}
            </Button>
          </div>

          {/* 快捷键提示 - 移动端隐藏 */}
          <div className="hidden sm:flex items-center gap-1 text-xs text-default-400">
            <kbd className="inline-flex items-center justify-center min-w-[20px] h-5 px-1.5 font-sans text-[11px] bg-default-100 border border-default-200 rounded">
              {isMac ? "⌘" : "Ctrl"}
            </kbd>
            <span>+</span>
            <kbd className="inline-flex items-center justify-center min-w-[20px] h-5 px-1.5 font-sans text-[11px] bg-default-100 border border-default-200 rounded">
              S
            </kbd>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// src/views/system/settings-management/components/FloatingSaveButton.vue
<template>
  <Transition name="float-save">
    <div v-if="hasChanges" class="floating-save-button">
      <div class="save-content">
        <span class="save-text">有未保存的更改</span>
        <el-button type="primary" :loading="loading" @click="handleSave">
          <el-icon v-if="!loading"><Check /></el-icon>
          {{ loading ? "保存中..." : "保存设置" }}
        </el-button>
      </div>
      <div class="keyboard-hint">
        <kbd>{{ isMac ? "⌘" : "Ctrl" }}</kbd>
        <span>+</span>
        <kbd>S</kbd>
      </div>
    </div>
  </Transition>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed } from "vue";
import { Check } from "@element-plus/icons-vue";

const props = defineProps<{
  hasChanges: boolean;
  loading?: boolean;
}>();

const emit = defineEmits<{
  (e: "save"): void;
}>();

const isMac = computed(
  () => navigator.platform.toUpperCase().indexOf("MAC") >= 0
);

const handleSave = () => {
  emit("save");
};

// 监听快捷键
const handleKeydown = (e: KeyboardEvent) => {
  if ((e.metaKey || e.ctrlKey) && e.key === "s") {
    e.preventDefault();
    if (props.hasChanges && !props.loading) {
      handleSave();
    }
  }
};

onMounted(() => {
  window.addEventListener("keydown", handleKeydown);
});

onUnmounted(() => {
  window.removeEventListener("keydown", handleKeydown);
});
</script>

<style scoped lang="scss">
.floating-save-button {
  position: fixed;
  bottom: 24px;
  right: 24px;
  z-index: 1000;
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 12px 20px;
  background: var(--el-bg-color);
  border-radius: 12px;
  box-shadow:
    0 4px 24px rgba(0, 0, 0, 0.12),
    0 0 0 1px var(--el-border-color-lighter);
  backdrop-filter: blur(8px);
}

.save-content {
  display: flex;
  align-items: center;
  gap: 12px;
}

.save-text {
  font-size: 14px;
  color: var(--el-text-color-regular);
}

.keyboard-hint {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  color: var(--el-text-color-secondary);

  kbd {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: 20px;
    height: 20px;
    padding: 0 6px;
    font-family: inherit;
    font-size: 11px;
    background: var(--el-fill-color);
    border: 1px solid var(--el-border-color);
    border-radius: 4px;
  }
}

// 动画
.float-save-enter-active,
.float-save-leave-active {
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.float-save-enter-from,
.float-save-leave-to {
  opacity: 0;
  transform: translateY(20px);
}

// ==================== 平板端适配 ====================
@media (max-width: 1024px) {
  .floating-save-button {
    bottom: 20px;
    right: 20px;
    gap: 12px;
    padding: 10px 16px;
  }
}

// ==================== 移动端适配 ====================
@media (max-width: 768px) {
  .floating-save-button {
    bottom: 16px;
    right: 16px;
    left: 16px;
    gap: 12px;
    padding: 12px 16px;
    justify-content: space-between;
  }

  .save-content {
    gap: 10px;
    flex: 1;
  }

  .save-text {
    font-size: 13px;
  }

  // 移动端隐藏键盘快捷键提示
  .keyboard-hint {
    display: none;
  }
}

// ==================== 小屏移动端适配 ====================
@media (max-width: 480px) {
  .floating-save-button {
    bottom: 12px;
    right: 12px;
    left: 12px;
    padding: 10px 12px;
  }

  .save-text {
    font-size: 12px;
  }

  .save-content {
    gap: 8px;

    .el-button {
      padding: 8px 12px;
      font-size: 13px;
    }
  }
}
</style>
