// src/views/system/theme-mall/components/ThemeConfigDialog.vue
<!--
 * @Description: 主题配置对话框
 * @Author: 安知鱼
 * @Date: 2025-01-24
-->
<template>
  <el-dialog
    v-model="visible"
    :title="`${themeName} - 主题配置`"
    width="720px"
    :close-on-click-modal="false"
    :close-on-press-escape="false"
    destroy-on-close
    @close="handleClose"
  >
    <div v-loading="loading" class="theme-config-content">
      <!-- 空配置状态 -->
      <el-empty
        v-if="!loading && settingGroups.length === 0"
        description="该主题暂无可配置项"
        :image-size="120"
      />

      <!-- 配置表单 -->
      <el-form
        v-else
        ref="formRef"
        :model="configValues"
        label-position="top"
        class="config-form"
      >
        <!-- 分组标签页 -->
        <el-tabs v-model="activeGroup" type="border-card" class="config-tabs">
          <el-tab-pane
            v-for="group in settingGroups"
            :key="group.group"
            :label="group.label"
            :name="group.group"
          >
            <div class="group-fields">
              <template v-for="field in group.fields" :key="field.name">
                <!-- 根据条件显示字段 -->
                <el-form-item
                  v-if="shouldShowField(field)"
                  :label="field.label"
                  :prop="field.name"
                  :required="field.required"
                  class="config-field"
                >
                  <!-- 字段描述 -->
                  <template v-if="field.description" #label>
                    <div class="field-label">
                      <span>{{ field.label }}</span>
                      <el-tooltip :content="field.description" placement="top">
                        <el-icon class="help-icon"><QuestionFilled /></el-icon>
                      </el-tooltip>
                    </div>
                  </template>

                  <!-- 文本输入 -->
                  <el-input
                    v-if="field.type === 'text'"
                    v-model="configValues[field.name]"
                    :placeholder="field.placeholder || `请输入${field.label}`"
                    clearable
                  />

                  <!-- 多行文本 -->
                  <el-input
                    v-else-if="field.type === 'textarea'"
                    v-model="configValues[field.name]"
                    type="textarea"
                    :rows="4"
                    :placeholder="field.placeholder || `请输入${field.label}`"
                  />

                  <!-- 数字输入 -->
                  <el-input-number
                    v-else-if="field.type === 'number'"
                    v-model="configValues[field.name]"
                    :min="field.validation?.min"
                    :max="field.validation?.max"
                    :placeholder="field.placeholder"
                    controls-position="right"
                    class="number-input"
                  />

                  <!-- 下拉选择 -->
                  <el-select
                    v-else-if="field.type === 'select'"
                    v-model="configValues[field.name]"
                    :placeholder="field.placeholder || `请选择${field.label}`"
                    clearable
                    class="select-input"
                  >
                    <el-option
                      v-for="option in field.options"
                      :key="String(option.value)"
                      :label="option.label"
                      :value="option.value"
                    />
                  </el-select>

                  <!-- 颜色选择器 -->
                  <div v-else-if="field.type === 'color'" class="color-field">
                    <el-color-picker
                      v-model="configValues[field.name]"
                      show-alpha
                    />
                    <el-input
                      v-model="configValues[field.name]"
                      :placeholder="field.placeholder || '#000000'"
                      class="color-input"
                    />
                  </div>

                  <!-- 开关 -->
                  <el-switch
                    v-else-if="field.type === 'switch'"
                    v-model="configValues[field.name]"
                    active-text="开启"
                    inactive-text="关闭"
                  />

                  <!-- 图片上传/URL -->
                  <div v-else-if="field.type === 'image'" class="image-field">
                    <el-input
                      v-model="configValues[field.name]"
                      :placeholder="
                        field.placeholder || '输入图片URL或上传图片'
                      "
                      clearable
                    >
                      <template #append>
                        <el-button
                          :icon="Picture"
                          @click="selectImage(field.name)"
                        >
                          选择
                        </el-button>
                      </template>
                    </el-input>
                    <!-- 图片预览 -->
                    <div v-if="configValues[field.name]" class="image-preview">
                      <img
                        :src="configValues[field.name]"
                        alt="预览"
                        @error="handleImageError"
                      />
                    </div>
                  </div>

                  <!-- 代码编辑器 -->
                  <el-input
                    v-else-if="field.type === 'code'"
                    v-model="configValues[field.name]"
                    type="textarea"
                    :rows="6"
                    :placeholder="field.placeholder || '请输入代码'"
                    class="code-input"
                  />
                </el-form-item>
              </template>
            </div>
          </el-tab-pane>
        </el-tabs>
      </el-form>
    </div>

    <template #footer>
      <div class="dialog-footer">
        <el-button @click="handleClose">取消</el-button>
        <el-button type="default" @click="resetToDefault"> 恢复默认 </el-button>
        <el-button
          type="primary"
          :loading="saving"
          :disabled="settingGroups.length === 0"
          @click="handleSave"
        >
          保存配置
        </el-button>
      </div>
    </template>
  </el-dialog>
</template>

<script lang="ts" setup>
import { ref, watch, computed } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { QuestionFilled, Picture } from "@element-plus/icons-vue";
import { themeMallApi } from "@/api/theme-mall";
import type {
  ThemeSettingGroup,
  ThemeSettingField
} from "@/api/theme-mall/type";

// Props
const props = defineProps<{
  modelValue: boolean;
  themeName: string;
}>();

// Emits
const emit = defineEmits<{
  (e: "update:modelValue", value: boolean): void;
  (e: "saved"): void;
}>();

// 响应式数据
const visible = computed({
  get: () => props.modelValue,
  set: value => emit("update:modelValue", value)
});

const loading = ref(false);
const saving = ref(false);
const settingGroups = ref<ThemeSettingGroup[]>([]);
const configValues = ref<Record<string, any>>({});
const defaultValues = ref<Record<string, any>>({});
const activeGroup = ref("");
const formRef = ref();

// 监听对话框打开
watch(
  () => props.modelValue,
  async newVal => {
    if (newVal && props.themeName) {
      await loadThemeConfig();
    }
  }
);

// 加载主题配置
const loadThemeConfig = async () => {
  loading.value = true;
  try {
    // 并行获取配置定义和用户配置
    const [settingsRes, configRes] = await Promise.all([
      themeMallApi.getThemeSettings(props.themeName),
      themeMallApi.getUserThemeConfig(props.themeName)
    ]);

    if (settingsRes.code === 200) {
      settingGroups.value = settingsRes.data || [];

      // 设置默认激活的分组
      if (settingGroups.value.length > 0) {
        activeGroup.value = settingGroups.value[0].group;
      }

      // 提取默认值
      defaultValues.value = {};
      for (const group of settingGroups.value) {
        for (const field of group.fields) {
          if (field.default !== undefined) {
            defaultValues.value[field.name] = field.default;
          }
        }
      }
    }

    if (configRes.code === 200) {
      // 合并默认值和用户配置
      configValues.value = {
        ...defaultValues.value,
        ...(configRes.data || {})
      };
    } else {
      configValues.value = { ...defaultValues.value };
    }
  } catch (error: any) {
    console.error("加载主题配置失败:", error);
    ElMessage.error(error.message || "加载主题配置失败");
  } finally {
    loading.value = false;
  }
};

// 判断字段是否应该显示
const shouldShowField = (field: ThemeSettingField): boolean => {
  if (!field.condition) {
    return true;
  }

  const { field: depField, operator, value } = field.condition;
  const currentValue = configValues.value[depField];

  switch (operator) {
    case "eq":
      return currentValue === value;
    case "neq":
      return currentValue !== value;
    case "contains":
      return String(currentValue).includes(String(value));
    case "gt":
      return Number(currentValue) > Number(value);
    case "lt":
      return Number(currentValue) < Number(value);
    default:
      return true;
  }
};

// 保存配置
const handleSave = async () => {
  saving.value = true;
  try {
    const response = await themeMallApi.saveUserThemeConfig({
      theme_name: props.themeName,
      config: configValues.value
    });

    if (response.code === 200) {
      ElMessage.success("配置保存成功");
      emit("saved");
      handleClose();
    } else {
      throw new Error(response.message || "保存失败");
    }
  } catch (error: any) {
    console.error("保存主题配置失败:", error);
    ElMessage.error(error.message || "保存主题配置失败");
  } finally {
    saving.value = false;
  }
};

// 恢复默认值
const resetToDefault = async () => {
  try {
    await ElMessageBox.confirm("确定要恢复所有配置为默认值吗？", "恢复默认", {
      confirmButtonText: "确定",
      cancelButtonText: "取消",
      type: "warning"
    });

    configValues.value = { ...defaultValues.value };
    ElMessage.success("已恢复默认配置");
  } catch {
    // 用户取消
  }
};

// 关闭对话框
const handleClose = () => {
  visible.value = false;
  settingGroups.value = [];
  configValues.value = {};
  activeGroup.value = "";
};

// 选择图片（这里可以集成文件管理器）
const selectImage = (fieldName: string) => {
  ElMessage.info("图片选择功能可以集成文件管理器");
};

// 图片加载错误处理
const handleImageError = (event: Event) => {
  const img = event.target as HTMLImageElement;
  img.style.display = "none";
};
</script>

<style scoped lang="scss">
.theme-config-content {
  min-height: 300px;
  max-height: 60vh;
  overflow-y: auto;
}

.config-form {
  .config-tabs {
    :deep(.el-tabs__header) {
      background: var(--el-bg-color);
    }

    :deep(.el-tabs__content) {
      padding: 20px;
    }
  }

  .group-fields {
    display: flex;
    flex-direction: column;
    gap: 16px;
  }

  .config-field {
    margin-bottom: 0;

    .field-label {
      display: flex;
      align-items: center;
      gap: 6px;

      .help-icon {
        color: var(--el-text-color-secondary);
        font-size: 14px;
        cursor: help;
      }
    }
  }

  .number-input {
    width: 200px;
  }

  .select-input {
    width: 100%;
  }

  .color-field {
    display: flex;
    align-items: center;
    gap: 12px;

    .color-input {
      flex: 1;
      max-width: 200px;
    }
  }

  .image-field {
    .image-preview {
      margin-top: 12px;
      max-width: 200px;
      border-radius: 8px;
      overflow: hidden;
      border: 1px solid var(--el-border-color);

      img {
        width: 100%;
        height: auto;
        display: block;
      }
    }
  }

  .code-input {
    :deep(.el-textarea__inner) {
      font-family: "Fira Code", "Monaco", monospace;
      font-size: 13px;
    }
  }
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}
</style>

// src/components/admin/themes/ThemeConfigDialog.tsx
"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import {
  ModalBody,
  ModalFooter,
  Button,
  Input,
  Select,
  SelectItem,
  Switch,
  Tabs,
  Tab,
  Spinner,
  addToast,
} from "@heroui/react";
import { AdminDialog } from "@/components/admin/AdminDialog";
import { Settings2 } from "lucide-react";
import { themeMallApi } from "@/lib/api/theme-mall";
import type { ThemeSettingGroup, ThemeSettingField } from "@/types/theme-mall";

interface ThemeConfigDialogProps {
  themeName: string | null;
  onClose: () => void;
}

export function ThemeConfigDialog({ themeName, onClose }: ThemeConfigDialogProps) {
  const isOpen = !!themeName;

  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [settingGroups, setSettingGroups] = useState<ThemeSettingGroup[]>([]);
  const [configValues, setConfigValues] = useState<Record<string, unknown>>({});
  const [defaultValues, setDefaultValues] = useState<Record<string, unknown>>({});
  const [activeGroup, setActiveGroup] = useState("");

  // 加载主题配置
  useEffect(() => {
    if (!themeName) return;
    let cancelled = false;

    const load = async () => {
      setLoading(true);
      try {
        const [settings, config] = await Promise.all([
          themeMallApi.getThemeSettings(themeName),
          themeMallApi.getUserThemeConfig(themeName),
        ]);

        if (cancelled) return;

        const groups = settings ?? [];
        setSettingGroups(groups);

        if (groups.length > 0) {
          setActiveGroup(groups[0].group);
        }

        // 提取默认值
        const defaults: Record<string, unknown> = {};
        for (const group of groups) {
          for (const field of group.fields) {
            if (field.default !== undefined) {
              defaults[field.name] = field.default;
            }
          }
        }
        setDefaultValues(defaults);

        // 合并默认值和用户配置
        setConfigValues({ ...defaults, ...(config ?? {}) });
      } catch (e) {
        addToast({ title: e instanceof Error ? e.message : "加载主题配置失败", color: "danger", timeout: 3000 });
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    load();
    return () => {
      cancelled = true;
    };
  }, [themeName]);

  // 字段变更
  const updateField = useCallback((name: string, value: unknown) => {
    setConfigValues(prev => ({ ...prev, [name]: value }));
  }, []);

  // 判断字段是否显示（对齐 anheyu-app shouldShowField）
  const shouldShowField = useCallback(
    (field: ThemeSettingField): boolean => {
      if (!field.condition) return true;
      const { field: depField, operator, value } = field.condition;
      const currentValue = configValues[depField];
      switch (operator) {
        case "eq":
          return currentValue === value;
        case "neq":
          return currentValue !== value;
        case "contains":
          return String(currentValue).includes(String(value));
        case "gt":
          return Number(currentValue) > Number(value);
        case "lt":
          return Number(currentValue) < Number(value);
        default:
          return true;
      }
    },
    [configValues]
  );

  // 保存
  const handleSave = useCallback(async () => {
    if (!themeName) return;
    setSaving(true);
    try {
      await themeMallApi.saveUserThemeConfig({ theme_name: themeName, config: configValues });
      addToast({ title: "配置保存成功", color: "success", timeout: 3000 });
      onClose();
    } catch (e) {
      addToast({ title: e instanceof Error ? e.message : "保存失败", color: "danger", timeout: 3000 });
    } finally {
      setSaving(false);
    }
  }, [themeName, configValues, onClose]);

  // 恢复默认
  const handleReset = useCallback(() => {
    setConfigValues({ ...defaultValues });
    addToast({ title: "已恢复默认配置", color: "success", timeout: 2000 });
  }, [defaultValues]);

  // 关闭清理
  const handleClose = useCallback(() => {
    setSettingGroups([]);
    setConfigValues({});
    setActiveGroup("");
    onClose();
  }, [onClose]);

  // 当前分组
  const currentGroup = useMemo(() => settingGroups.find(g => g.group === activeGroup), [settingGroups, activeGroup]);

  return (
    <AdminDialog
      isOpen={isOpen}
      onOpenChange={open => {
        if (!open) handleClose();
      }}
      size="2xl"
      scrollBehavior="inside"
      header={{
        title: `${themeName} - 主题配置`,
        description: "调整主题参数并实时保存配置",
        icon: Settings2,
      }}
    >
      <ModalBody className="gap-0 p-0">
        {loading ? (
          <div className="flex items-center justify-center py-16">
            <Spinner size="sm" label="加载配置中..." />
          </div>
        ) : settingGroups.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
            <p className="text-sm">该主题暂无可配置项</p>
          </div>
        ) : (
          <div className="flex flex-col">
            {/* 分组 Tabs */}
            {settingGroups.length > 1 && (
              <div className="px-6 border-b border-border/50">
                <Tabs
                  aria-label="配置分组"
                  variant="underlined"
                  size="sm"
                  selectedKey={activeGroup}
                  onSelectionChange={key => setActiveGroup(key as string)}
                  classNames={{ tabList: "gap-4", tab: "px-0 h-8", cursor: "w-full" }}
                >
                  {settingGroups.map(g => (
                    <Tab key={g.group} title={g.label} />
                  ))}
                </Tabs>
              </div>
            )}

            {/* 配置字段 */}
            <div className="px-6 py-4 flex flex-col gap-4 max-h-[50vh] overflow-y-auto">
              {currentGroup?.fields.map(field => {
                if (!shouldShowField(field)) return null;
                const value = configValues[field.name];

                return (
                  <div key={field.name}>
                    {field.type === "text" && (
                      <Input
                        label={field.label}
                        description={field.description}
                        placeholder={field.placeholder || `请输入${field.label}`}
                        value={String(value ?? "")}
                        onValueChange={v => updateField(field.name, v)}
                        isRequired={field.required}
                        size="sm"
                      />
                    )}
                    {field.type === "textarea" && (
                      <Input
                        label={field.label}
                        description={field.description}
                        placeholder={field.placeholder || `请输入${field.label}`}
                        value={String(value ?? "")}
                        onValueChange={v => updateField(field.name, v)}
                        isRequired={field.required}
                        size="sm"
                      />
                    )}
                    {field.type === "number" && (
                      <Input
                        label={field.label}
                        description={field.description}
                        placeholder={field.placeholder}
                        type="number"
                        value={String(value ?? "")}
                        onValueChange={v => updateField(field.name, v === "" ? "" : Number(v))}
                        isRequired={field.required}
                        size="sm"
                      />
                    )}
                    {field.type === "select" && field.options && (
                      <Select
                        label={field.label}
                        description={field.description}
                        placeholder={field.placeholder || `请选择${field.label}`}
                        selectedKeys={value != null ? [String(value)] : []}
                        onSelectionChange={keys => {
                          const selected = Array.from(keys)[0];
                          updateField(field.name, selected);
                        }}
                        isRequired={field.required}
                        size="sm"
                      >
                        {field.options.map(opt => (
                          <SelectItem key={String(opt.value)}>{opt.label}</SelectItem>
                        ))}
                      </Select>
                    )}
                    {field.type === "switch" && (
                      <div className="flex items-center justify-between">
                        <div>
                          <p className="text-sm font-medium">{field.label}</p>
                          {field.description && (
                            <p className="text-xs text-muted-foreground mt-0.5">{field.description}</p>
                          )}
                        </div>
                        <Switch isSelected={!!value} onValueChange={v => updateField(field.name, v)} size="sm" />
                      </div>
                    )}
                    {field.type === "color" && (
                      <Input
                        label={field.label}
                        description={field.description}
                        placeholder={field.placeholder || "#000000"}
                        value={String(value ?? "")}
                        onValueChange={v => updateField(field.name, v)}
                        size="sm"
                        startContent={
                          <div
                            className="w-4 h-4 rounded-full border border-border/50"
                            style={{ backgroundColor: String(value || "#000") }}
                          />
                        }
                      />
                    )}
                    {field.type === "image" && (
                      <Input
                        label={field.label}
                        description={field.description}
                        placeholder={field.placeholder || "输入图片URL"}
                        value={String(value ?? "")}
                        onValueChange={v => updateField(field.name, v)}
                        size="sm"
                      />
                    )}
                    {field.type === "code" && (
                      <Input
                        label={field.label}
                        description={field.description}
                        placeholder={field.placeholder || "请输入代码"}
                        value={String(value ?? "")}
                        onValueChange={v => updateField(field.name, v)}
                        size="sm"
                        classNames={{ input: "font-mono text-xs" }}
                      />
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </ModalBody>
      <ModalFooter>
        <Button variant="flat" onPress={handleClose}>
          取消
        </Button>
        <Button variant="flat" onPress={handleReset} isDisabled={settingGroups.length === 0}>
          恢复默认
        </Button>
        <Button color="primary" onPress={handleSave} isLoading={saving} isDisabled={settingGroups.length === 0}>
          保存配置
        </Button>
      </ModalFooter>
    </AdminDialog>
  );
}
